import type { Metadata } from "next";
import { PageHero } from "@/components/page-hero";

const policies: Record<string, { title: string; eyebrow: string; intro: string; sections: Array<[string, string]> }> = {
  "giao-hang": { title: "Chính sách giao hàng", eyebrow: "Delivery · 配送", intro: "Phí và trạng thái được tính theo cấu hình vận chuyển và đơn hàng thật của bạn.", sections: [["Phí vận chuyển", "Phí cụ thể hiển thị trước khi bạn xác nhận đặt hàng."], ["Theo dõi", "Mỗi mốc xác nhận, bàn giao, giao hàng và hoàn tất đều lưu lịch sử thật."], ["Hỗ trợ", "Liên hệ hotline JAPANO nếu trạng thái không cập nhật sau thời gian dự kiến."]] },
  "doi-tra": { title: "Chính sách đổi & trả", eyebrow: "Returns · 返品", intro: "Đổi trả dựa trên trạng thái giao nhận và thời hạn JAPANO công bố.", sections: [["Điều kiện", "Sản phẩm còn nguyên trạng, đúng dòng đơn và chưa vượt thời hạn đổi trả."], ["Đổi size", "Ưu tiên đổi size khi tồn kho còn; không cam kết size không có thật."], ["Hoàn tiền", "Khoản hoàn đi qua đúng cổng đã thanh toán; COD được xử lý theo quy trình thủ công được công bố."]] },
  "bao-mat": { title: "Quyền riêng tư", eyebrow: "Privacy · 個人情報", intro: "Dữ liệu mua sắm cần lưu khác với ảnh cá nhân dùng tạm cho AI.", sections: [["Ảnh thử đồ", "Ảnh cá nhân không được lưu vào cơ sở dữ liệu, nhật ký hệ thống hay bộ nhớ đệm."], ["Tài khoản", "Phiên đăng nhập nằm trong cookie bảo mật, không đọc được bằng mã JavaScript của trang."], ["Dữ liệu mua hàng", "Đơn, địa chỉ và giao dịch chỉ dùng cho vận hành, hỗ trợ và nghĩa vụ pháp lý."]] },
};

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; return { title: policies[slug]?.title || "Chính sách", alternates: { canonical: `/chinh-sach/${slug}` } }; }
export default async function PolicyPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const policy = policies[slug] || policies["bao-mat"]; return <div className="page-shell policy-page"><PageHero eyebrow={policy.eyebrow} title={policy.title} copy={policy.intro} /><div className="policy-copy">{policy.sections.map(([title, copy], index) => <section key={title}><span>{String(index + 1).padStart(2, "0")}</span><div><h2>{title}</h2><p>{copy}</p></div></section>)}</div><p className="policy-disclaimer">Đây là bản tóm tắt. Chính sách giao nhận được công bố trong hệ thống JAPANO là căn cứ cuối cùng khi xử lý đơn.</p></div>; }
