/* ============ BỘ BIỂU TƯỢNG — Ionicons, đúng bộ mà app đang dùng ============
 * Trang quản trị trước đây dùng emoji (🧾 💳 👘 ⭐ …). Emoji do HỆ ĐIỀU HÀNH vẽ:
 * mỗi máy một nét, một bảng màu, không chỉnh được kích thước hay màu theo trạng
 * thái — nên khung quản trị không bao giờ trông cùng một sản phẩm với app.
 *
 * Ở đây nạp thẳng Ionicons.ttf lấy từ @expo/vector-icons (chính tệp phông mà
 * mobile/components/ui.tsx render) và tra mã ký tự từ glyphmap của bộ đó. Nhờ
 * vậy biểu tượng trên web và trên điện thoại là MỘT, tự ăn theo màu chữ
 * (currentColor) và cỡ chữ, không cần mạng và không thêm thư viện nào.
 *
 * Tệp này SINH RA từ glyphmaps/Ionicons.json — thêm biểu tượng thì thêm tên vào
 * danh sách rồi tra lại mã, đừng gõ tay mã ký tự.
 * ========================================================================= */
const ICON_GLYPH={
  'speedometer-outline':'\uee91',
  'receipt-outline':'\uee10',
  'card-outline':'\ueae9',
  'return-down-back-outline':'\uee3a',
  'shirt-outline':'\uee82',
  'star-outline':'\uee9a',
  'shield-checkmark-outline':'\uee7a',
  'people-outline':'\ueda4',
  'map-outline':'\ued44',
  'megaphone-outline':'\ued50',
  'folder-open-outline':'\uec28',
  'pricetag-outline':'\uedec',
  'flag-outline':'\uec12',
  'image-outline':'\uec90',
  'settings-outline':'\uee6d',
  'search-outline':'\uee64',
  'notifications-outline':'\ued80',
  'refresh-outline':'\uee19',
  'log-out-outline':'\uecd2',
  'menu-outline':'\ued53',
  'chevron-down':'\ueb33',
  'chevron-forward':'\ueb3c',
  'chevron-back':'\ueb2a',
  'chevron-up':'\ueb42',
  'close':'\ueb4b',
  'checkmark':'\ueb1e',
  'add':'\uea04',
  'remove':'\uee21',
  'ellipsis-horizontal':'\uebcf',
  'filter-outline':'\uec06',
  'open-outline':'\ued89',
  'copy-outline':'\ueb91',
  'download-outline':'\uebbb',
  'create-outline':'\ueb94',
  'trash-outline':'\ueef7',
  'eye-outline':'\uebeb',
  'eye-off-outline':'\uebe9',
  'save-outline':'\uee52',
  'send-outline':'\uee67',
  'checkmark-circle-outline':'\ueb20',
  'close-circle-outline':'\ueb4d',
  'alert-circle-outline':'\uea15',
  'information-circle-outline':'\uec9a',
  'warning-outline':'\uef2a',
  'help-circle-outline':'\uec7f',
  'lock-closed-outline':'\uecc9',
  'sparkles-outline':'\uee8e',
  'cloud-offline-outline':'\ueb5c',
  'cash-outline':'\ueb07',
  'wallet-outline':'\uef27',
  'cube-outline':'\ueb9a',
  'bag-check-outline':'\uea5d',
  'cart-outline':'\ueb04',
  'trending-up-outline':'\ueefd',
  'trending-down-outline':'\ueefa',
  'time-outline':'\ueedf',
  'car-outline':'\ueae3',
  'person-outline':'\uedad',
  'diamond-outline':'\ueba3',
  'analytics-outline':'\uea1d',
  'bar-chart-outline':'\uea71',
  'pie-chart-outline':'\uedb9',
  'pulse-outline':'\uedf8',
  'flash-outline':'\uec1b',
  'albums-outline':'\uea11',
  'archive-outline':'\uea26',
  'business-outline':'\ueac8',
  'call-outline':'\ueada',
  'mail-outline':'\ued35',
  'location-outline':'\uecc6',
  'calendar-outline':'\uead7',
  'link-outline':'\uecba',
  'checkmark-done-outline':'\ueb26',
  'swap-horizontal-outline':'\ueeb2',
  'arrow-up':'\uea46',
  'arrow-down':'\uea2e',
  'ban-outline':'\uea6b',
  'key-outline':'\ueca5',
  'server-outline':'\uee6a',
  'cloud-done-outline':'\ueb56',
  'hardware-chip-outline':'\uec66',
  'color-palette-outline':'\ueb7f',
  'resize-outline':'\uee34',
  'grid-outline':'\uec57',
  'list-outline':'\uecc0',
  'options-outline':'\ued8c',
  'print-outline':'\uedf2',
  'share-social-outline':'\uee76',
  'heart-outline':'\uec78',
  'chatbubble-ellipses-outline':'\ueb14',
  'thumbs-up-outline':'\ueed6',
  'thumbs-down-outline':'\ueed3',
  'ticket-outline':'\ueedc',
  'gift-outline':'\uec39',
  'cloud-upload-outline':'\ueb61',
  'star':'\uee96',
  'storefront-outline':'\ueea9',
  'cube':'\ueb99',
  'shirt':'\uee81',
  'receipt':'\uee0f',
  'card':'\ueae8',
  'people':'\ueda0',
  'pricetags-outline':'\uedef',
  'document-text-outline':'\uebb5',
  'videocam-outline':'\uef12',
  'camera-outline':'\ueadd',
  'sync-outline':'\ueebb',
  'bag-handle-outline':'\uea60',
  'trophy-outline':'\uef03',
  'rocket-outline':'\uee49',
  'bulb-outline':'\ueac2',
  'construct-outline':'\ueb88',
  'git-branch-outline':'\uec3c',
  'layers-outline':'\uecb1',
  'shield-outline':'\uee7f',
  'globe-outline':'\uec51',
  'chatbubbles-outline':'\ueb19',
  'happy-outline':'\uec63',
  'sad-outline':'\uee4f',
};

/* icon('cart-outline')            → cỡ mặc định, ăn theo màu chữ hiện tại
 * icon('cart-outline',18)         → ép cỡ
 * icon('cart-outline',18,'accent')→ thêm lớp màu ngữ nghĩa */
function icon(name,size,cls){
  const glyph=ICON_GLYPH[name];
  if(!glyph)return '';
  const style=size?` style="font-size:${size}px"`:'';
  return `<i class="ion${cls?' '+cls:''}" aria-hidden="true"${style}>${glyph}</i>`;
}
