import React from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { goBackOrReplace } from '../lib/navigation';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Feather } from '@expo/vector-icons';
import { useApp } from '../context/AppContext';
import { SafeImage } from '../components/SafeImage';
import { fontFamily, radius, scaleFont, shadow } from '../lib/styles';
import AppButton from '../components/AppButton';

export default function CartScreen() {
  const { theme, cart, removeFromCart, formatCurrency, isLoggedIn } = useApp(); const insets = useSafeAreaInsets();
  const total = cart.reduce((sum, item) => sum + item.price, 0);
  return <View style={{ flex: 1, backgroundColor: theme.background, paddingTop: insets.top + 10 }}><View style={styles.header}><Pressable onPress={() => goBackOrReplace()} style={[styles.round, { backgroundColor: theme.card, borderColor: theme.border }]}><Feather name="arrow-left" size={21} color={theme.text} /></Pressable><Text style={[styles.title, { color: theme.heading, fontFamily: fontFamily(theme), fontSize: scaleFont(theme, 28) }]}>Giỏ hàng</Text></View><ScrollView contentContainerStyle={{ padding: 16, paddingBottom: 170, gap: 12 }}>{cart.length ? cart.map((item, idx) => <View key={`${item.id}-${idx}`} style={[styles.item, { backgroundColor: theme.card, borderColor: theme.border }, shadow(theme)]}><SafeImage source={{ uri: item.image }} style={styles.image} resizeMode="contain" /><View style={{ flex: 1 }}><Text numberOfLines={2} style={[styles.itemName, { color: theme.heading }]}>{item.name}</Text><Text style={[styles.price, { color: theme.primary }]}>{formatCurrency(item.price)}</Text></View><Pressable onPress={() => removeFromCart(`${item.id}-${idx}`)}><Feather name="trash-2" size={20} color={theme.primary} /></Pressable></View>) : <View style={[styles.empty, { backgroundColor: theme.card, borderColor: theme.border }]}><Text style={[styles.emptyTitle, { color: theme.heading }]}>Giỏ hàng trống</Text><Text style={[styles.emptyText, { color: theme.muted }]}>Bạn có thể lướt sản phẩm thoải mái, nhưng để mua hàng cần đăng nhập.</Text><AppButton title="Xem sản phẩm" icon="shopping-bag" full={false} onPress={() => router.push('/shop')} /></View>}</ScrollView><View style={[styles.footer, { backgroundColor: theme.card, borderTopColor: theme.border, paddingBottom: insets.bottom + 14 }]}><View><Text style={[styles.totalLabel, { color: theme.muted }]}>Tổng cộng</Text><Text style={[styles.total, { color: theme.heading }]}>{formatCurrency(total)}</Text></View><AppButton title="Thanh toán" icon="credit-card" full={false} onPress={() => isLoggedIn ? router.push('/checkout') : Alert.alert('Cần đăng nhập', 'Bạn cần đăng nhập để thanh toán và lưu lịch sử mua hàng.', [{ text: 'Để sau' }, { text: 'Đăng nhập', onPress: () => router.push('/login') }])} /></View></View>;
}
const styles = StyleSheet.create({ header: { paddingHorizontal: 16, paddingBottom: 12, flexDirection: 'row', alignItems: 'center', gap: 11 }, round: { width: 46, height: 45, borderRadius: 0, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, title: { fontWeight: '900' }, item: { borderWidth: 1, borderRadius: 0, padding: 10, flexDirection: 'row', gap: 12, alignItems: 'center' }, image: { width: 84, height: 84, borderRadius: 0}, itemName: { fontWeight: '900', fontSize: 15 }, price: { fontWeight: '900', marginTop: 6 }, empty: { borderWidth: 1, borderRadius: 0, padding: 18, gap: 12 }, emptyTitle: { fontSize: 24, fontWeight: '900' }, emptyText: { fontSize: 14, lineHeight: 21 }, btn: { alignSelf: 'flex-start', borderRadius: 0, paddingHorizontal: 16, paddingVertical: 12 }, btnText: { fontWeight: '900' }, footer: { position: 'absolute', left: 0, right: 0, bottom: 0, borderTopWidth: 1, padding: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 14 }, totalLabel: { fontSize: 12, fontWeight: '800' }, total: { fontSize: 21, fontWeight: '900' }, checkout: { minWidth: 150, height: 54, borderRadius: 0, alignItems: 'center', justifyContent: 'center' }, checkoutText: { fontWeight: '900', letterSpacing: 1.2 } });
