$ErrorActionPreference = 'Continue'
Set-Location -LiteralPath 'C:\jp\v37'
Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
if (Test-Path '.\.venv\Scripts\Activate.ps1') { . '.\.venv\Scripts\Activate.ps1' }
$env:PYTHON_BIN = Join-Path (Get-Location) '.venv\Scripts\python.exe'
$env:PYTHONIOENCODING = 'utf-8'
$env:PYTHONUTF8 = '1'
$env:CUDA_VISIBLE_DEVICES = '0'
$env:OLLAMA_URL = 'http://localhost:11434'
$env:OLLAMA_MODEL = 'qwen3:14b'
$env:OLLAMA_TIMEOUT_MS = '60000'
$env:OLLAMA_COOLDOWN_MS = '15000'
$env:AI_LOCAL_FIRST = '1'
$env:JAPANO_GPU_PROFILE = 'NVIDIA_5060TI_16GB'
$env:LOCAL_AI_CHAT_FAST = 'qwen3:8b'
$env:LOCAL_AI_CHAT_BEST = 'qwen3:14b'
$env:LOCAL_AI_VISION = 'llama3.2-vision:11b'
$env:LOCAL_AI_EMBED_TEXT = 'nomic-embed-text'
$env:LOCAL_AI_IMAGE_FAST = 'SDXL-Turbo'
$env:LOCAL_AI_IMAGE_BEST = 'FLUX.2-klein-4B'
$env:LOCAL_AI_TRYON = 'CatVTON'
$env:LOCAL_AI_SEGMENT = 'SAM2/BiRefNet'
Write-Host '[JAPANO] Backend local-first dang chay tai http://localhost:4000'
npm run start-server
