// Góc chụp ("scene") dùng để ghép người vào phong cảnh Nhật Bản.
//
// KHÁC với japanSceneBackgrounds.js: file kia là ảnh minh hoạ ĐỊA ĐIỂM cho màn
// Khám phá; file này là ảnh đã được duyệt để ĐẶT NGƯỜI vào. Hai việc khác nhau,
// và trộn lẫn chúng chính là nguyên nhân của ảnh Naoshima cũ: một bức chụp từ
// trên thuyền, 45% dưới khung là mặt biển, nên người bị đặt đứng giữa nước.
//
// Vì sao mỗi scene cần toạ độ riêng: dùng một điểm đặt chân chung (giữa khung,
// sát đáy) chỉ đúng khi mọi ảnh đều có mặt đất ở đáy khung — điều gần như không
// bao giờ xảy ra. Ảnh chụp ngang tầm mắt có đường chân trời khác nhau, mặt đất
// bắt đầu ở độ cao khác nhau, và landmark nằm ở chỗ khác nhau.
//
// Ảnh phải tự tải từ nguồn có giấy phép rõ ràng. KHÔNG mặc định mọi ảnh
// Wikimedia đều dùng được — mỗi file dưới đây đã được tra giấy phép riêng.
//
// Tỉ lệ đều là 0..1 theo khung ảnh, không phải pixel, nên đổi độ phân giải ảnh
// không làm sai vị trí.
//
// Ảnh được TẢI VỀ và phục vụ từ mobile/assets/japan-scenes/ thay vì hotlink
// Wikimedia. Ba lý do: Wikimedia chỉ trả về đúng những kích thước đã render sẵn
// (xin 1800px cho ra HTTP 400 trong khi 1920px thì được), hotlink phụ thuộc một
// dịch vụ ngoài tầm kiểm soát, và tự phục vụ thì lúc ghép ảnh không cần gọi
// mạng ra ngoài lần nào. Giấy phép vẫn phải ghi công đầy đủ ở dưới.
const path = require('path');
const { publicTravelPoses, recommendedTravelPose } = require('./travelPoses');

const SCENE_DIR = path.join(__dirname, '..', '..', 'mobile', 'assets', 'japan-scenes');

/**
 * Các địa điểm trong catalog cũ ban đầu chỉ có ảnh minh hoạ. Factory này giữ
 * phần metadata lặp lại đồng nhất, còn vùng đứng/landmark vẫn phải khai báo tay
 * theo từng ảnh. Không có fallback tọa độ chung: thiếu polygon là validator đỏ.
 */
function catalogScene({
  id, spotPlace, spotPrefecture, name, mood, timeOfDay = 'day', season = 'all',
  sourceUrl, author, license, licenseUrl, groundType, wardrobeNote,
  modestDress = false, composition,
}) {
  return {
    id,
    spotPlace,
    spotPrefecture,
    name,
    mood,
    timeOfDay,
    season,
    imageFile: `${id}.jpg`,
    thumbnailUrl: `/assets/japan-scenes/${id}-thumb.webp`,
    sourceUrl,
    author,
    license,
    licenseUrl,
    attribution: `${author}, ${license}, qua Wikimedia Commons`,
    checkedAt: '2026-09-01',
    groundType,
    wardrobeNote,
    ...(modestDress ? { modestDress: true } : {}),
    composition,
  };
}

// 21 góc dưới đây phủ nốt toàn bộ 35 địa điểm đang hiển thị ở app/web. Ảnh
// minh hoạ chụp từ trên cao, trên thuyền hoặc chỉ thấy mặt nước đã bị loại.
const CATALOG_COVERAGE_SCENES = [
  catalogScene({
    id: 'arashiyama-bamboo-path',
    spotPlace: 'Rừng tre Arashiyama',
    spotPrefecture: 'Kyoto',
    name: 'Lối tre Sagano',
    mood: 'Tĩnh lặng',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Bamboo_Grove,_Arashiyama,_Kyoto,_Japan.jpg',
    author: 'Basile Morin',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    groundType: 'đường đất',
    wardrobeNote: 'Lối tre xanh sâu hợp kimono sáng màu, trắng, be hoặc đỏ trầm.',
    composition: {
      horizonY: 0.38, groundLineY: 0.48,
      footAnchor: { x: 0.50, y: 0.95 },
      personHeightRatio: { min: 0.40, preferred: 0.56, max: 0.68 },
      safeZone: { x: 0.28, y: 0.26, width: 0.44, height: 0.70 },
      landmarkAvoidRects: [{ x: 0.0, y: 0.0, width: 0.18, height: 1.0 }, { x: 0.84, y: 0.0, width: 0.16, height: 1.0 }],
      groundPolygon: [[0.16, 0.48], [0.84, 0.48], [0.92, 1.0], [0.08, 1.0]],
      lightDirection: 'upper-left', lightTemperature: 'cool',
      shadowOpacity: 0.20, shadowBlur: 15, shadowAngle: 14,
      personSlots: [{ id: 'left', label: 'Lệch trái trên lối tre', x: 0.43 }, { id: 'right', label: 'Lệch phải trên lối tre', x: 0.57 }],
    },
  }),
  catalogScene({
    id: 'kyoto-gion-hanamikoji-street',
    spotPlace: 'Phố cổ Gion',
    spotPrefecture: 'Kyoto',
    name: 'Phố Hanamikoji',
    mood: 'Cổ kính',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:150124_Gion_Kyoto_Japan01s3.jpg',
    author: '663highland',
    license: 'CC BY 2.5',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.5/',
    groundType: 'đường lát',
    wardrobeNote: 'Mặt tiền machiya nâu đỏ tôn kimono, haori và trang phục màu kem.',
    composition: {
      horizonY: 0.42, groundLineY: 0.55,
      footAnchor: { x: 0.50, y: 0.95 },
      personHeightRatio: { min: 0.34, preferred: 0.48, max: 0.60 },
      safeZone: { x: 0.34, y: 0.38, width: 0.32, height: 0.58 },
      landmarkAvoidRects: [{ x: 0.0, y: 0.0, width: 0.24, height: 0.82 }, { x: 0.78, y: 0.0, width: 0.22, height: 0.82 }],
      groundPolygon: [[0.25, 0.55], [0.72, 0.55], [0.90, 1.0], [0.10, 1.0]],
      lightDirection: 'upper-left', lightTemperature: 'warm',
      shadowOpacity: 0.19, shadowBlur: 15, shadowAngle: 15,
      personSlots: [{ id: 'center', label: 'Giữa phố lát đá', x: 0.50 }],
    },
  }),
  catalogScene({
    id: 'kawaguchi-lakeside-promenade',
    spotPlace: 'Hồ Kawaguchi',
    spotPrefecture: 'Yamanashi',
    name: 'Đường dạo ven hồ nhìn núi Phú Sĩ',
    mood: 'Khoáng đạt',
    season: 'autumn',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Kawaguchiko,_Part_III_-_Kawaguchiko6783.jpg',
    author: 'lumoplank',
    license: 'CC0 1.0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    groundType: 'đường gạch',
    wardrobeNote: 'Lá thu và núi Phú Sĩ hợp áo khoác kem, đỏ gạch hoặc xanh chàm.',
    composition: {
      horizonY: 0.39, groundLineY: 0.50,
      footAnchor: { x: 0.65, y: 0.95 },
      personHeightRatio: { min: 0.32, preferred: 0.46, max: 0.57 },
      safeZone: { x: 0.50, y: 0.38, width: 0.30, height: 0.58 },
      landmarkAvoidRects: [{ x: 0.77, y: 0.08, width: 0.23, height: 0.38 }],
      groundPolygon: [[0.0, 0.48], [0.18, 0.48], [0.80, 1.0], [0.0, 1.0]],
      lightDirection: 'upper-left', lightTemperature: 'golden',
      shadowOpacity: 0.20, shadowBlur: 17, shadowAngle: 12,
      personSlots: [{ id: 'promenade', label: 'Trên đường gạch ven hồ', x: 0.65 }],
    },
  }),
  catalogScene({
    id: 'nara-park-lawn',
    spotPlace: 'Công viên Nara',
    spotPrefecture: 'Nara',
    name: 'Bãi cỏ cùng đàn hươu',
    mood: 'Thân thiện',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Nara_Park01bns3200.jpg',
    author: '663highland',
    license: 'CC BY 2.5',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.5/',
    groundType: 'cỏ',
    wardrobeNote: 'Bãi cỏ xanh hợp trang phục sáng và họa tiết nhỏ; giữ khoảng cách với hươu.',
    composition: {
      horizonY: 0.36, groundLineY: 0.46,
      footAnchor: { x: 0.78, y: 0.94 },
      personHeightRatio: { min: 0.34, preferred: 0.48, max: 0.58 },
      safeZone: { x: 0.66, y: 0.38, width: 0.30, height: 0.58 },
      landmarkAvoidRects: [{ x: 0.02, y: 0.32, width: 0.56, height: 0.36 }],
      groundPolygon: [[0.0, 0.46], [1.0, 0.46], [1.0, 1.0], [0.0, 1.0]],
      lightDirection: 'upper-left', lightTemperature: 'neutral',
      shadowOpacity: 0.18, shadowBlur: 18, shadowAngle: 14,
      personSlots: [{ id: 'right-lawn', label: 'Bãi cỏ trống bên phải', x: 0.78 }],
    },
  }),
  catalogScene({
    id: 'shibuya-sky-roof-deck',
    spotPlace: 'Đài quan sát Shibuya',
    spotPrefecture: 'Tokyo',
    name: 'Sàn gỗ SHIBUYA SKY',
    mood: 'Hiện đại',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Shibuya_Scramble_Square_SHIBUYA_SKY_(52978968068).jpg',
    author: 'Dick Thomas Johnson',
    license: 'CC BY 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.0/',
    groundType: 'sàn gỗ',
    wardrobeNote: 'Đường chân trời Tokyo và sàn gỗ hợp outfit tối giản, đơn sắc hoặc ánh kim.',
    composition: {
      horizonY: 0.34, groundLineY: 0.64,
      footAnchor: { x: 0.52, y: 0.94 },
      personHeightRatio: { min: 0.30, preferred: 0.44, max: 0.54 },
      safeZone: { x: 0.39, y: 0.40, width: 0.30, height: 0.57 },
      landmarkAvoidRects: [{ x: 0.02, y: 0.40, width: 0.28, height: 0.28 }],
      groundPolygon: [[0.0, 0.64], [1.0, 0.64], [1.0, 1.0], [0.0, 1.0]],
      lightDirection: 'upper-right', lightTemperature: 'neutral',
      shadowOpacity: 0.16, shadowBlur: 20, shadowAngle: -13,
      personSlots: [{ id: 'deck', label: 'Sàn gỗ trung tâm', x: 0.52 }],
    },
  }),
  catalogScene({
    id: 'omoide-yokocho-lane',
    spotPlace: 'Omoide Yokocho',
    spotPrefecture: 'Tokyo',
    name: 'Ngõ đèn lồng Shinjuku',
    mood: 'Đời thường',
    timeOfDay: 'evening',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Entrance_to_Omoide_Yokocho.jpg',
    author: 'Grendelkhan',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    groundType: 'lối bê tông',
    wardrobeNote: 'Biển hiệu và đèn lồng nhiều màu hợp outfit trung tính hoặc denim tối.',
    composition: {
      horizonY: 0.34, groundLineY: 0.43,
      footAnchor: { x: 0.50, y: 0.95 },
      personHeightRatio: { min: 0.38, preferred: 0.52, max: 0.64 },
      safeZone: { x: 0.31, y: 0.30, width: 0.38, height: 0.67 },
      landmarkAvoidRects: [{ x: 0.0, y: 0.0, width: 0.20, height: 1.0 }, { x: 0.82, y: 0.0, width: 0.18, height: 1.0 }],
      groundPolygon: [[0.20, 0.43], [0.80, 0.43], [0.90, 1.0], [0.10, 1.0]],
      lightDirection: 'upper-left', lightTemperature: 'neon',
      shadowOpacity: 0.23, shadowBlur: 13, shadowAngle: 16,
      personSlots: [{ id: 'lane', label: 'Giữa ngõ', x: 0.50 }],
    },
  }),
  catalogScene({
    id: 'otaru-canal-promenade',
    spotPlace: 'Kênh Otaru',
    spotPrefecture: 'Hokkaido',
    name: 'Lối đi bộ ven kênh',
    mood: 'Lãng mạn',
    timeOfDay: 'evening',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Otaru_Canal_HDR1.jpg',
    author: 'Tan Wei Liang Byorn',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    groundType: 'đường lát',
    wardrobeNote: 'Đèn vàng và kho gạch hợp áo khoác dài, màu kem, nâu hoặc đỏ rượu.',
    composition: {
      horizonY: 0.42, groundLineY: 0.55,
      footAnchor: { x: 0.18, y: 0.94 },
      personHeightRatio: { min: 0.32, preferred: 0.46, max: 0.56 },
      safeZone: { x: 0.04, y: 0.38, width: 0.28, height: 0.58 },
      landmarkAvoidRects: [{ x: 0.36, y: 0.28, width: 0.64, height: 0.66 }],
      groundPolygon: [[0.0, 0.55], [0.18, 0.55], [0.36, 1.0], [0.0, 1.0]],
      lightDirection: 'upper-right', lightTemperature: 'warm',
      shadowOpacity: 0.20, shadowBlur: 14, shadowAngle: -12,
      personSlots: [{ id: 'left-promenade', label: 'Lối đi bộ bên trái', x: 0.18 }],
    },
  }),
  catalogScene({
    id: 'shirakawago-ogimachi-lawn',
    spotPlace: 'Làng Shirakawa-go',
    spotPrefecture: 'Gifu',
    name: 'Bãi cỏ làng Ogimachi',
    mood: 'Thanh bình',
    season: 'autumn',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:20171030_Shiragawa_2396_(25263880528).jpg',
    author: 'Ray Swi-hymn',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    groundType: 'cỏ',
    wardrobeNote: 'Nhà gassho-zukuri và cỏ thu hợp áo len, áo khoác và tông đất.',
    composition: {
      horizonY: 0.43, groundLineY: 0.58,
      footAnchor: { x: 0.42, y: 0.94 },
      personHeightRatio: { min: 0.32, preferred: 0.46, max: 0.56 },
      safeZone: { x: 0.28, y: 0.38, width: 0.30, height: 0.58 },
      landmarkAvoidRects: [{ x: 0.54, y: 0.28, width: 0.42, height: 0.34 }],
      groundPolygon: [[0.0, 0.58], [1.0, 0.58], [1.0, 1.0], [0.0, 1.0]],
      lightDirection: 'upper-left', lightTemperature: 'neutral',
      shadowOpacity: 0.18, shadowBlur: 18, shadowAngle: 14,
      personSlots: [{ id: 'lawn', label: 'Bãi cỏ trước làng', x: 0.42 }],
    },
  }),
  catalogScene({
    id: 'hitachi-seaside-cycling-path',
    spotPlace: 'Công viên Hitachi Seaside',
    spotPrefecture: 'Ibaraki',
    name: 'Lối dạo giữa vườn hoa',
    mood: 'Tươi sáng',
    season: 'spring',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Cycling_Course_(Hitachi_Seaside_Park).JPG',
    author: 'Abasaa',
    license: 'Public domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    groundType: 'đường nhựa',
    wardrobeNote: 'Vườn hoa nhiều màu hợp trang phục pastel hoặc trắng để không tranh màu với nền.',
    composition: {
      horizonY: 0.37, groundLineY: 0.54,
      footAnchor: { x: 0.20, y: 0.94 },
      personHeightRatio: { min: 0.30, preferred: 0.42, max: 0.52 },
      safeZone: { x: 0.05, y: 0.39, width: 0.30, height: 0.57 },
      landmarkAvoidRects: [{ x: 0.38, y: 0.40, width: 0.62, height: 0.50 }],
      groundPolygon: [[0.0, 0.54], [0.26, 0.54], [0.42, 1.0], [0.0, 1.0]],
      lightDirection: 'upper-left', lightTemperature: 'neutral',
      shadowOpacity: 0.17, shadowBlur: 18, shadowAngle: 15,
      personSlots: [{ id: 'path', label: 'Lối dạo bên trái', x: 0.20 }],
    },
  }),
  catalogScene({
    id: 'osaka-nishinomaru-lawn',
    spotPlace: 'Lâu đài Osaka',
    spotPrefecture: 'Osaka',
    name: 'Bãi cỏ Nishinomaru',
    mood: 'Hùng vĩ',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Nishinomaru_Garden_Osaka_Castle06s4s4272.jpg',
    author: '663highland',
    license: 'CC BY 2.5',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.5/',
    groundType: 'cỏ',
    wardrobeNote: 'Bãi cỏ phẳng và lâu đài trắng xanh hợp kimono hoặc trang phục màu đậm.',
    composition: {
      horizonY: 0.38, groundLineY: 0.54,
      footAnchor: { x: 0.60, y: 0.94 },
      personHeightRatio: { min: 0.32, preferred: 0.46, max: 0.56 },
      safeZone: { x: 0.47, y: 0.38, width: 0.28, height: 0.58 },
      landmarkAvoidRects: [{ x: 0.68, y: 0.02, width: 0.28, height: 0.43 }],
      groundPolygon: [[0.0, 0.54], [1.0, 0.54], [1.0, 1.0], [0.0, 1.0]],
      lightDirection: 'upper-left', lightTemperature: 'neutral',
      shadowOpacity: 0.18, shadowBlur: 18, shadowAngle: 13,
      personSlots: [{ id: 'lawn', label: 'Bãi cỏ trước lâu đài', x: 0.60 }],
    },
  }),
  catalogScene({
    id: 'kenrokuen-kotojitoro-bank',
    spotPlace: 'Vườn Kenrokuen',
    spotPrefecture: 'Ishikawa',
    name: 'Bờ cỏ cạnh đèn đá Kotojitoro',
    mood: 'Thanh nhã',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:The_rainbow_bridge_and_the_Kotojitoro_stone_lantern_in_the_Kenrokuen_Garden_in_Kanazawa_(53621075708).jpg',
    author: 'Winniepix',
    license: 'CC BY 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.0/',
    groundType: 'bờ cỏ',
    wardrobeNote: 'Đèn đá, hồ và tán thông hợp kimono nhẹ, màu kem, xanh rêu hoặc đỏ trầm.',
    composition: {
      horizonY: 0.33, groundLineY: 0.50,
      footAnchor: { x: 0.82, y: 0.72 },
      personHeightRatio: { min: 0.25, preferred: 0.34, max: 0.43 },
      safeZone: { x: 0.69, y: 0.15, width: 0.29, height: 0.60 },
      landmarkAvoidRects: [{ x: 0.20, y: 0.33, width: 0.47, height: 0.57 }],
      groundPolygon: [[0.67, 0.50], [1.0, 0.48], [1.0, 0.76], [0.66, 0.76]],
      lightDirection: 'upper-left', lightTemperature: 'neutral',
      shadowOpacity: 0.17, shadowBlur: 14, shadowAngle: 12,
      personSlots: [{ id: 'right-bank', label: 'Bờ cỏ bên phải', x: 0.82 }],
    },
  }),
  catalogScene({
    id: 'jigokudani-snow-trail',
    spotPlace: 'Công viên khỉ tuyết Jigokudani',
    spotPrefecture: 'Nagano',
    name: 'Đường tuyết vào Yaen-koen',
    mood: 'Mùa đông',
    season: 'winter',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Road_to_Jigokudani_Yaen-koen_03.JPG',
    author: 'Abasaa',
    license: 'Public domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    groundType: 'đường tuyết',
    wardrobeNote: 'Nền tuyết và rừng tối hợp áo khoác đậm, khăn len và giày cổ cao.',
    composition: {
      horizonY: 0.35, groundLineY: 0.47,
      footAnchor: { x: 0.55, y: 0.95 },
      personHeightRatio: { min: 0.34, preferred: 0.48, max: 0.58 },
      safeZone: { x: 0.38, y: 0.38, width: 0.35, height: 0.58 },
      landmarkAvoidRects: [{ x: 0.0, y: 0.0, width: 0.26, height: 0.86 }, { x: 0.82, y: 0.0, width: 0.18, height: 0.86 }],
      groundPolygon: [[0.34, 0.45], [0.78, 0.45], [0.95, 1.0], [0.18, 1.0]],
      lightDirection: 'upper-right', lightTemperature: 'cool',
      shadowOpacity: 0.16, shadowBlur: 20, shadowAngle: -10,
      personSlots: [{ id: 'snow-path', label: 'Giữa đường tuyết', x: 0.55 }],
    },
  }),
  catalogScene({
    id: 'kamakura-daibutsu-courtyard',
    spotPlace: 'Tượng Đại Phật Kamakura',
    spotPrefecture: 'Kanagawa',
    name: 'Sân trước Đại Phật',
    mood: 'Trang nghiêm',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:230128_Kamakura_Daibutsu_Japan04s3.jpg',
    author: '663highland',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    groundType: 'sân sỏi',
    wardrobeNote: 'Nền tượng đồng xanh hợp trang phục kín đáo, trắng, chàm hoặc màu đất.',
    modestDress: true,
    composition: {
      horizonY: 0.54, groundLineY: 0.78,
      footAnchor: { x: 0.34, y: 0.95 },
      personHeightRatio: { min: 0.28, preferred: 0.40, max: 0.50 },
      safeZone: { x: 0.20, y: 0.40, width: 0.28, height: 0.57 },
      landmarkAvoidRects: [{ x: 0.46, y: 0.02, width: 0.34, height: 0.72 }],
      groundPolygon: [[0.0, 0.78], [1.0, 0.78], [1.0, 1.0], [0.0, 1.0]],
      lightDirection: 'upper-left', lightTemperature: 'neutral',
      shadowOpacity: 0.17, shadowBlur: 17, shadowAngle: 13,
      personSlots: [{ id: 'left-courtyard', label: 'Sân sỏi bên trái', x: 0.34 }],
    },
  }),
  catalogScene({
    id: 'sapporo-odori-tv-tower',
    spotPlace: 'Công viên Ōdōri',
    spotPrefecture: 'Hokkaido',
    name: 'Bãi cỏ nhìn tháp truyền hình',
    mood: 'Đô thị',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:20240923_Sapporo_Odori_Park.jpg',
    author: 'ノボホショコロトソ',
    license: 'CC BY 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
    groundType: 'bãi cỏ',
    wardrobeNote: 'Mảng xanh và tháp đỏ hợp trang phục trắng, navy, be hoặc phong cách đường phố.',
    composition: {
      horizonY: 0.58, groundLineY: 0.89,
      footAnchor: { x: 0.59, y: 0.95 },
      personHeightRatio: { min: 0.28, preferred: 0.38, max: 0.46 },
      safeZone: { x: 0.45, y: 0.38, width: 0.25, height: 0.59 },
      landmarkAvoidRects: [{ x: 0.69, y: 0.00, width: 0.14, height: 0.66 }],
      groundPolygon: [[0.0, 0.89], [1.0, 0.89], [1.0, 1.0], [0.0, 1.0]],
      lightDirection: 'upper-left', lightTemperature: 'neutral',
      shadowOpacity: 0.18, shadowBlur: 18, shadowAngle: 15,
      personSlots: [{ id: 'front-lawn', label: 'Bãi cỏ tiền cảnh', x: 0.59 }],
    },
  }),
  catalogScene({
    id: 'hirosaki-castle-lawn',
    spotPlace: 'Lâu đài Hirosaki',
    spotPrefecture: 'Aomori',
    name: 'Bãi cỏ trước tháp lâu đài',
    mood: 'Cổ điển',
    season: 'spring',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Hirosaki_Castle_Keep_Tower_20220508.jpg',
    author: '掬茶',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    groundType: 'cỏ',
    wardrobeNote: 'Lâu đài trắng và bãi cỏ hợp kimono, áo khoác pastel hoặc xanh chàm.',
    composition: {
      horizonY: 0.39, groundLineY: 0.56,
      footAnchor: { x: 0.67, y: 0.94 },
      personHeightRatio: { min: 0.30, preferred: 0.42, max: 0.52 },
      safeZone: { x: 0.54, y: 0.39, width: 0.29, height: 0.57 },
      landmarkAvoidRects: [{ x: 0.25, y: 0.05, width: 0.36, height: 0.50 }],
      groundPolygon: [[0.0, 0.56], [1.0, 0.56], [1.0, 1.0], [0.0, 1.0]],
      lightDirection: 'upper-left', lightTemperature: 'neutral',
      shadowOpacity: 0.18, shadowBlur: 18, shadowAngle: 13,
      personSlots: [{ id: 'right-lawn', label: 'Bãi cỏ bên phải', x: 0.67 }],
    },
  }),
  catalogScene({
    id: 'dogo-onsen-street',
    spotPlace: 'Suối nước nóng Dōgo Onsen',
    spotPrefecture: 'Ehime',
    name: 'Phố trước Dōgo Onsen Honkan',
    mood: 'Hoài cổ',
    timeOfDay: 'evening',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Dogo_onsen_honkan_long_exposure.jpg',
    author: 'Japanexperterna.se',
    license: 'CC BY-SA 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/',
    groundType: 'đường lát',
    wardrobeNote: 'Ánh đèn vàng trên nhà gỗ hợp yukata, áo khoác dài và tông nâu hoặc đỏ rượu.',
    composition: {
      horizonY: 0.45, groundLineY: 0.69,
      footAnchor: { x: 0.70, y: 0.94 },
      personHeightRatio: { min: 0.30, preferred: 0.42, max: 0.52 },
      safeZone: { x: 0.56, y: 0.39, width: 0.30, height: 0.57 },
      landmarkAvoidRects: [{ x: 0.03, y: 0.02, width: 0.54, height: 0.68 }],
      groundPolygon: [[0.0, 0.69], [1.0, 0.67], [1.0, 1.0], [0.0, 1.0]],
      lightDirection: 'upper-left', lightTemperature: 'warm',
      shadowOpacity: 0.22, shadowBlur: 14, shadowAngle: 12,
      personSlots: [{ id: 'right-street', label: 'Khoảng đường bên phải', x: 0.70 }],
    },
  }),
  catalogScene({
    id: 'churaumi-kuroshio-gallery',
    spotPlace: 'Thuỷ cung Churaumi',
    spotPrefecture: 'Okinawa',
    name: 'Sảnh bể Kuroshio',
    mood: 'Huyền ảo',
    timeOfDay: 'indoor',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Okinawa_Aquarium.jpg',
    author: 'Jordy Meow',
    license: 'CC BY-SA 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/',
    groundType: 'sàn phòng trưng bày',
    wardrobeNote: 'Ánh xanh của bể cá hợp đồ trắng, bạc, navy hoặc đen tối giản.',
    composition: {
      horizonY: 0.48, groundLineY: 0.72,
      footAnchor: { x: 0.84, y: 0.94 },
      personHeightRatio: { min: 0.26, preferred: 0.38, max: 0.48 },
      safeZone: { x: 0.70, y: 0.39, width: 0.28, height: 0.57 },
      landmarkAvoidRects: [{ x: 0.18, y: 0.10, width: 0.50, height: 0.54 }],
      groundPolygon: [[0.0, 0.72], [1.0, 0.72], [1.0, 1.0], [0.0, 1.0]],
      lightDirection: 'front', lightTemperature: 'cool',
      shadowOpacity: 0.18, shadowBlur: 16, shadowAngle: 0,
      personSlots: [{ id: 'right-gallery', label: 'Sàn trống bên phải', x: 0.84 }],
    },
  }),
  catalogScene({
    id: 'beppu-umi-jigoku-walkway',
    spotPlace: 'Suối nước nóng Beppu',
    spotPrefecture: 'Oita',
    name: 'Lối đi vườn Umi Jigoku',
    mood: 'Độc đáo',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Beppu_Umi-jigoku01n3200.jpg',
    author: '663highland',
    license: 'CC BY 2.5',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.5/',
    groundType: 'lối đi lát',
    wardrobeNote: 'Nhà mái tranh và vườn xanh hợp trang phục màu đất, trắng hoặc đỏ gạch.',
    composition: {
      horizonY: 0.40, groundLineY: 0.57,
      footAnchor: { x: 0.82, y: 0.94 },
      personHeightRatio: { min: 0.30, preferred: 0.42, max: 0.52 },
      safeZone: { x: 0.69, y: 0.39, width: 0.29, height: 0.57 },
      landmarkAvoidRects: [{ x: 0.02, y: 0.12, width: 0.57, height: 0.58 }],
      groundPolygon: [[0.50, 0.54], [1.0, 0.50], [1.0, 1.0], [0.0, 1.0], [0.0, 0.78]],
      lightDirection: 'upper-left', lightTemperature: 'neutral',
      shadowOpacity: 0.18, shadowBlur: 17, shadowAngle: 14,
      personSlots: [{ id: 'right-walkway', label: 'Lối đi bên phải', x: 0.82 }],
    },
  }),
  catalogScene({
    id: 'koyasan-danjo-garan-courtyard',
    spotPlace: 'Núi thiêng Koyasan',
    spotPrefecture: 'Wakayama',
    name: 'Sân Danjō Garan',
    mood: 'Trang nghiêm',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Danj%C3%B4-garan_(Wakayama_K%C5%8Dyasan)_Temple_hdsr_S5_tr02.jpg',
    author: 'Hyppolyte de Saint-Rambert',
    license: 'CC BY 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
    groundType: 'sân sỏi',
    wardrobeNote: 'Tháp son và rừng tuyết tùng hợp trang phục kín đáo, chàm, kem hoặc màu đất.',
    modestDress: true,
    composition: {
      horizonY: 0.41, groundLineY: 0.58,
      footAnchor: { x: 0.45, y: 0.95 },
      personHeightRatio: { min: 0.36, preferred: 0.50, max: 0.61 },
      safeZone: { x: 0.29, y: 0.34, width: 0.34, height: 0.63 },
      landmarkAvoidRects: [{ x: 0.66, y: 0.04, width: 0.30, height: 0.56 }],
      groundPolygon: [[0.12, 0.58], [0.82, 0.58], [0.96, 1.0], [0.04, 1.0]],
      lightDirection: 'upper-left', lightTemperature: 'neutral',
      shadowOpacity: 0.19, shadowBlur: 16, shadowAngle: 14,
      personSlots: [{ id: 'courtyard', label: 'Giữa sân Danjō Garan', x: 0.45 }],
    },
  }),
  catalogScene({
    id: 'takachiho-three-bridges-lookout',
    spotPlace: 'Hẻm núi Takachiho',
    spotPrefecture: 'Miyazaki',
    name: 'Nền đá đài ngắm Tam Cầu',
    mood: 'Hùng vĩ',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Miyazaki-ken_Takachiho-kyo_(Kyushu_hitchhike)_(9973801374).jpg',
    author: 'Peter Enyeart',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    groundType: 'nền đá',
    wardrobeNote: 'Vách đá xanh và cầu vòm hợp trang phục màu sáng, xanh lạnh hoặc đỏ trầm.',
    composition: {
      horizonY: 0.39, groundLineY: 0.54,
      footAnchor: { x: 0.20, y: 0.94 },
      personHeightRatio: { min: 0.32, preferred: 0.45, max: 0.55 },
      safeZone: { x: 0.05, y: 0.39, width: 0.30, height: 0.57 },
      landmarkAvoidRects: [{ x: 0.38, y: 0.02, width: 0.54, height: 0.50 }],
      groundPolygon: [[0.0, 0.53], [0.48, 0.53], [0.60, 1.0], [0.0, 1.0]],
      lightDirection: 'upper-left', lightTemperature: 'cool',
      shadowOpacity: 0.19, shadowBlur: 16, shadowAngle: 13,
      personSlots: [{ id: 'left-rock', label: 'Nền đá bên trái', x: 0.20 }],
    },
  }),
  catalogScene({
    id: 'kurashiki-hondori-street',
    spotPlace: 'Phố cổ Kurashiki Bikan',
    spotPrefecture: 'Okayama',
    name: 'Phố Honmachi lát đá',
    mood: 'Hoài cổ',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Kurashiki_Hondori_Shopping_street_-_panoramio_(1).jpg',
    author: 'DVMG',
    license: 'CC BY 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/3.0/',
    groundType: 'đường lát',
    wardrobeNote: 'Tường trắng và gỗ tối hợp kimono, haori hoặc outfit màu chàm và đỏ rượu.',
    composition: {
      horizonY: 0.38, groundLineY: 0.46,
      footAnchor: { x: 0.47, y: 0.95 },
      personHeightRatio: { min: 0.34, preferred: 0.48, max: 0.59 },
      safeZone: { x: 0.31, y: 0.37, width: 0.34, height: 0.60 },
      landmarkAvoidRects: [{ x: 0.0, y: 0.0, width: 0.20, height: 0.90 }, { x: 0.80, y: 0.0, width: 0.20, height: 0.90 }],
      groundPolygon: [[0.22, 0.45], [0.74, 0.45], [0.88, 1.0], [0.08, 1.0]],
      lightDirection: 'upper-left', lightTemperature: 'neutral',
      shadowOpacity: 0.20, shadowBlur: 15, shadowAngle: 14,
      personSlots: [{ id: 'center-street', label: 'Giữa phố Honmachi', x: 0.47 }],
    },
  }),
  // --- Bổ sung 2026-09-02 ------------------------------------------------
  // Hai địa điểm mới, đo hình học trên chính ảnh nguồn. Cả hai được chọn vì có
  // MẶT ĐẤT thật ở tiền cảnh — tiêu chí đã loại nhiều ứng viên khác trong cùng
  // đợt tìm: ảnh Kiyomizu-dera 5852px, CC BY-SA 4.0, rất đẹp nhưng chụp từ trên
  // cao qua thung lũng nên tiền cảnh là ngọn cây, không ai đứng vào được.
  catalogScene({
    id: 'meiji-jingu-torii-path',
    spotPlace: 'Đền Meiji Jingu',
    spotPrefecture: 'Tokyo',
    name: 'Cổng torii lối vào Meiji Jingu',
    mood: 'Trang nghiêm',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Meiji-jingu_Torii_2.jpg',
    author: 'Zairon',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    groundType: 'lối sỏi',
    wardrobeNote: 'Rừng cây tối và cổng gỗ trầm làm nền; kimono sáng màu hoặc haori đỏ/trắng nổi rõ nhất.',
    composition: {
      horizonY: 0.80, groundLineY: 0.86,
      // Đứng giữa hai cột torii, trên lối sỏi.
      footAnchor: { x: 0.50, y: 0.96 },
      // Đo lại trên ảnh ghép thật: ở 0.54 nhân vật cao gấp ~3,5 lần nhóm khách
      // đứng cùng lối sỏi phía sau nên đọc ra như người khổng lồ. 0.38 khớp với
      // phối cảnh lối đi lùi dần về cổng.
      personHeightRatio: { min: 0.28, preferred: 0.38, max: 0.48 },
      safeZone: { x: 0.38, y: 0.28, width: 0.26, height: 0.70 },
      // Hai cột torii: người không được chồng lên thân cột.
      landmarkAvoidRects: [
        { x: 0.30, y: 0.40, width: 0.08, height: 0.55 },
        { x: 0.63, y: 0.40, width: 0.09, height: 0.55 },
      ],
      groundPolygon: [[0.10, 0.88], [0.90, 0.88], [1.0, 1.0], [0.0, 1.0]],
      // Trời nhiều mây: bóng mềm và tán rộng, nhưng KHÔNG được bằng 0 — thiếu
      // bóng là thứ khiến người ghép trông như dán nổi trên nền.
      lightDirection: 'front', lightTemperature: 'cool',
      shadowOpacity: 0.30, shadowBlur: 26, shadowAngle: 8,
      personSlots: [
        { id: 'center', label: 'Giữa cổng torii', x: 0.50 },
        { id: 'left', label: 'Lệch trái trên lối sỏi', x: 0.44 },
      ],
    },
  }),
  catalogScene({
    id: 'iwakuni-kintaikyo-riverbank',
    spotPlace: 'Cầu Kintai-kyō',
    spotPrefecture: 'Yamaguchi',
    name: 'Bãi sỏi dưới cầu Kintai-kyō',
    mood: 'Khoáng đạt',
    timeOfDay: 'afternoon',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Iwakuni,_ponte_kintai-kyo,_00.jpg',
    author: 'Sailko',
    license: 'CC BY 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
    groundType: 'bãi sỏi',
    wardrobeNote: 'Nắng chiều ấm trên bãi sỏi xám; yukata màu lạnh hoặc xanh chàm tách nền tốt.',
    composition: {
      horizonY: 0.66, groundLineY: 0.72,
      // Khoảng sỏi trống giữa trụ cầu giữa (kết thúc ~0.47) và trụ phải (bắt đầu ~0.78).
      footAnchor: { x: 0.62, y: 0.94 },
      personHeightRatio: { min: 0.36, preferred: 0.52, max: 0.64 },
      safeZone: { x: 0.50, y: 0.30, width: 0.28, height: 0.65 },
      // Chỉ né THÂN TRỤ ĐÁ. Nhịp cầu phía trên là bầu trời/vòm gỗ, người đứng
      // dưới vòm là đúng bố cục chứ không phải lỗi — lấy cả bóng cầu làm vùng
      // cấm sẽ khiến safeZone chồng landmark 34% và trượt validator.
      landmarkAvoidRects: [
        { x: 0.40, y: 0.60, width: 0.08, height: 0.15 },
        { x: 0.78, y: 0.58, width: 0.08, height: 0.17 },
      ],
      groundPolygon: [[0.0, 0.74], [1.0, 0.74], [1.0, 1.0], [0.0, 1.0]],
      lightDirection: 'upper-right', lightTemperature: 'warm',
      shadowOpacity: 0.24, shadowBlur: 12, shadowAngle: -18,
      personSlots: [
        { id: 'center', label: 'Giữa bãi sỏi dưới nhịp cầu', x: 0.62 },
        { id: 'left', label: 'Lệch trái, lấy trọn ba nhịp', x: 0.55 },
      ],
    },
  }),
];

const SCENES = Object.freeze([
  {
    id: 'naoshima-miyanoura-promenade',
    spotPlace: 'Đảo nghệ thuật Naoshima',
    spotPrefecture: 'Kagawa',
    name: 'Quảng trường cảng Miyanoura',
    mood: 'Biểu tượng',
    timeOfDay: 'day',
    season: 'all',
    imageFile: 'naoshima-miyanoura-promenade.jpg',
    thumbnailUrl: '/assets/japan-scenes/naoshima-miyanoura-promenade-thumb.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Miyanoura_port06s3872.jpg',
    author: '663highland',
    license: 'CC BY 2.5',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.5/',
    attribution: '663highland, CC BY 2.5, qua Wikimedia Commons',
    checkedAt: '2026-08-29',
    groundType: 'bê tông',
    wardrobeNote: 'Nền bê tông xám và mái thép trắng làm nổi màu sáng và màu pastel.',
    composition: {
      horizonY: 0.31,
      groundLineY: 0.44,
      // Đặt lệch trái: mái canopy của bến phà là landmark, trải từ x≈0.28 sang phải.
      footAnchor: { x: 0.22, y: 0.86 },
      personHeightRatio: { min: 0.34, preferred: 0.50, max: 0.62 },
      safeZone: { x: 0.05, y: 0.30, width: 0.34, height: 0.66 },
      landmarkAvoidRects: [{ x: 0.28, y: 0.10, width: 0.72, height: 0.36 }],
      groundPolygon: [[0.0, 0.46], [1.0, 0.44], [1.0, 1.0], [0.0, 1.0]],
      lightDirection: 'upper-right',
      lightTemperature: 'neutral',
      shadowOpacity: 0.16,
      shadowBlur: 22,
      shadowAngle: -14,
      personSlots: [{ id: 'left', label: 'Khoảng trống bên trái', x: 0.22 }],
    },
  },
  {
    id: 'naoshima-honmura-street',
    spotPlace: 'Đảo nghệ thuật Naoshima',
    spotPrefecture: 'Kagawa',
    name: 'Phố cổ Honmura',
    mood: 'Yên tĩnh',
    timeOfDay: 'day',
    season: 'all',
    imageFile: 'naoshima-honmura-street.jpg',
    thumbnailUrl: '/assets/japan-scenes/naoshima-honmura-street-thumb.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Naoshima_honmura_gallery.jpg',
    author: 'Artandgeograph',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: 'Artandgeograph, CC BY-SA 4.0, qua Wikimedia Commons',
    checkedAt: '2026-08-29',
    groundType: 'đường nhựa',
    wardrobeNote: 'Gỗ cháy yakisugi màu tối làm nền tương phản mạnh cho kimono và đồ sáng màu.',
    composition: {
      horizonY: 0.55,
      groundLineY: 0.76,
      footAnchor: { x: 0.17, y: 0.94 },
      personHeightRatio: { min: 0.34, preferred: 0.46, max: 0.58 },
      safeZone: { x: 0.03, y: 0.34, width: 0.28, height: 0.62 },
      landmarkAvoidRects: [{ x: 0.30, y: 0.02, width: 0.68, height: 0.76 }],
      groundPolygon: [[0.0, 0.80], [1.0, 0.74], [1.0, 1.0], [0.0, 1.0]],
      lightDirection: 'upper-left',
      lightTemperature: 'neutral',
      shadowOpacity: 0.20,
      shadowBlur: 16,
      shadowAngle: 18,
      personSlots: [{ id: 'left', label: 'Bên trái', x: 0.17 }],
    },
  },
  {
    id: 'fushimi-inari-senbon-torii',
    spotPlace: 'Đền Fushimi Inari',
    spotPrefecture: 'Kyoto',
    name: 'Lối Senbon Torii',
    mood: 'Biểu tượng',
    timeOfDay: 'day',
    season: 'all',
    imageFile: 'fushimi-inari-senbon-torii.jpg',
    thumbnailUrl: '/assets/japan-scenes/fushimi-inari-senbon-torii-thumb.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Fushimi-Inari-Shrine-Senbon-Torii-2018-Luka-Peternel.jpg',
    author: 'Luka Peternel',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: 'Luka Peternel, CC BY-SA 4.0, qua Wikimedia Commons',
    checkedAt: '2026-08-29',
    groundType: 'đá lát',
    wardrobeNote: 'Cổng son đỏ rất mạnh màu: đồ trung tính, trắng hoặc chàm nổi hơn đồ đỏ/cam.',
    // Đền thờ — trang phục phải kín đáo. Cờ này chặn gợi ý đồ bơi ở bước
    // recommendations, không phải ở bước ghép ảnh.
    modestDress: true,
    composition: {
      horizonY: 0.44,
      groundLineY: 0.70,
      footAnchor: { x: 0.45, y: 0.95 },
      personHeightRatio: { min: 0.42, preferred: 0.60, max: 0.72 },
      safeZone: { x: 0.24, y: 0.26, width: 0.42, height: 0.70 },
      // Hành lang torii bao quanh chứ không nằm sau lưng, nên vùng "tránh" là
      // hai bên cột: đứng giữa lối là đúng chỗ và không che gì.
      landmarkAvoidRects: [
        { x: 0.0, y: 0.0, width: 0.22, height: 1.0 },
        { x: 0.70, y: 0.0, width: 0.30, height: 1.0 },
      ],
      groundPolygon: [[0.22, 0.72], [0.72, 0.70], [1.0, 1.0], [0.0, 1.0]],
      lightDirection: 'upper-left',
      lightTemperature: 'warm',
      shadowOpacity: 0.24,
      shadowBlur: 14,
      shadowAngle: 22,
      personSlots: [
        { id: 'center', label: 'Giữa lối', x: 0.45 },
        { id: 'right', label: 'Bên phải', x: 0.58 },
      ],
    },
  },
  {
    id: 'itsukushima-mikasanohama-sando',
    spotPlace: 'Đền Itsukushima · Miyajima',
    spotPrefecture: 'Hiroshima',
    name: 'Lối cát Mikasanohama',
    mood: 'Trang nghiêm',
    timeOfDay: 'day',
    season: 'all',
    imageFile: 'itsukushima-mikasanohama-sando.jpg',
    thumbnailUrl: '/assets/japan-scenes/itsukushima-mikasanohama-sando-thumb.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Sando_of_Itsukushima_Shrine_3.jpg',
    author: 'そらみみ',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: 'そらみみ, CC BY-SA 4.0, qua Wikimedia Commons',
    checkedAt: '2026-09-01',
    groundType: 'lối cát',
    wardrobeNote: 'Lối cát sáng và đèn đá ven biển hợp kimono, yukata và trang phục chàm hoặc đỏ trầm.',
    modestDress: true,
    composition: {
      horizonY: 0.32,
      groundLineY: 0.48,
      // Cắt dọc quanh nửa phải của ảnh để loại vùng biển bên trái; người chỉ
      // được đứng trên lối cát rộng, giữa thân cây và đèn đá.
      footAnchor: { x: 0.61, y: 0.95 },
      personHeightRatio: { min: 0.34, preferred: 0.46, max: 0.56 },
      safeZone: { x: 0.48, y: 0.36, width: 0.28, height: 0.60 },
      landmarkAvoidRects: [
        { x: 0.18, y: 0.0, width: 0.27, height: 0.92 },
        { x: 0.77, y: 0.04, width: 0.18, height: 0.58 },
      ],
      groundPolygon: [[0.44, 0.48], [1.0, 0.44], [1.0, 1.0], [0.35, 1.0]],
      lightDirection: 'upper-left',
      lightTemperature: 'neutral',
      shadowOpacity: 0.18,
      shadowBlur: 17,
      shadowAngle: 14,
      personSlots: [{ id: 'sando', label: 'Giữa lối cát', x: 0.61 }],
    },
  },
  {
    id: 'ginzan-onsen-promenade',
    spotPlace: 'Suối nước nóng Ginzan',
    spotPrefecture: 'Yamagata',
    name: 'Phố ryokan ven sông',
    mood: 'Hoài cổ',
    timeOfDay: 'day',
    season: 'autumn',
    imageFile: 'ginzan-onsen-promenade.jpg',
    thumbnailUrl: '/assets/japan-scenes/ginzan-onsen-promenade-thumb.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Ginzan_Onsen_-_GinzanOnsen7426.jpg',
    author: 'lumoplank',
    license: 'CC0 1.0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: 'lumoplank, CC0 1.0, qua Wikimedia Commons',
    checkedAt: '2026-09-01',
    groundType: 'đường lát',
    wardrobeNote: 'Nhà ryokan gỗ và lá thu vàng hợp áo khoác, kimono màu trầm và bảng màu kem.',
    composition: {
      horizonY: 0.40,
      groundLineY: 0.53,
      footAnchor: { x: 0.42, y: 0.96 },
      personHeightRatio: { min: 0.36, preferred: 0.48, max: 0.58 },
      safeZone: { x: 0.27, y: 0.36, width: 0.34, height: 0.62 },
      landmarkAvoidRects: [
        { x: 0.0, y: 0.0, width: 0.23, height: 0.66 },
        { x: 0.62, y: 0.0, width: 0.38, height: 0.70 },
      ],
      groundPolygon: [[0.27, 0.52], [0.60, 0.52], [0.82, 1.0], [0.05, 1.0]],
      lightDirection: 'upper-left',
      lightTemperature: 'warm',
      shadowOpacity: 0.20,
      shadowBlur: 15,
      shadowAngle: 12,
      personSlots: [{ id: 'promenade', label: 'Giữa phố đi bộ', x: 0.42 }],
    },
  },
  {
    id: 'himeji-sannomaru-square',
    spotPlace: 'Lâu đài Himeji',
    spotPrefecture: 'Hyogo',
    name: 'Bãi cỏ Sannomaru',
    mood: 'Hùng vĩ',
    timeOfDay: 'day',
    season: 'all',
    imageFile: 'himeji-sannomaru-square.jpg',
    thumbnailUrl: '/assets/japan-scenes/himeji-sannomaru-square-thumb.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Tenshu_of_Himeji_Castle_from_Sannomaru_Square_4.jpg',
    author: 'そらみみ',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: 'そらみみ, CC BY-SA 4.0, qua Wikimedia Commons',
    checkedAt: '2026-09-01',
    groundType: 'cỏ',
    wardrobeNote: 'Bãi cỏ trung tính và tường thành trắng hợp kimono, yukata và trang phục màu đậm.',
    composition: {
      horizonY: 0.42,
      groundLineY: 0.50,
      footAnchor: { x: 0.35, y: 0.94 },
      personHeightRatio: { min: 0.36, preferred: 0.50, max: 0.60 },
      safeZone: { x: 0.10, y: 0.38, width: 0.34, height: 0.58 },
      landmarkAvoidRects: [{ x: 0.44, y: 0.17, width: 0.28, height: 0.28 }],
      groundPolygon: [[0.0, 0.50], [1.0, 0.50], [1.0, 1.0], [0.0, 1.0]],
      lightDirection: 'upper-left',
      lightTemperature: 'neutral',
      shadowOpacity: 0.18,
      shadowBlur: 18,
      shadowAngle: 14,
      personSlots: [{ id: 'left', label: 'Bãi cỏ trống bên trái', x: 0.35 }],
    },
  },
  {
    id: 'sensoji-hozomon-courtyard',
    spotPlace: 'Chùa Sensō-ji · Asakusa',
    spotPrefecture: 'Tokyo',
    name: 'Sân trước cổng Hōzōmon',
    mood: 'Rực rỡ',
    timeOfDay: 'day',
    season: 'all',
    imageFile: 'sensoji-hozomon-courtyard.jpg',
    thumbnailUrl: '/assets/japan-scenes/sensoji-hozomon-courtyard-thumb.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Hozomon_(main_gate),_Sensoji_Temple,_Asakusa,_Tokyo.jpg',
    author: 'Daderot',
    license: 'Public domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    attribution: 'Daderot, Public domain, qua Wikimedia Commons',
    checkedAt: '2026-09-01',
    groundType: 'đá lát',
    wardrobeNote: 'Cổng son và đèn lồng rất mạnh màu; đồ trắng, chàm hoặc pastel sẽ nổi rõ.',
    modestDress: true,
    composition: {
      horizonY: 0.56,
      groundLineY: 0.78,
      footAnchor: { x: 0.84, y: 0.96 },
      personHeightRatio: { min: 0.32, preferred: 0.38, max: 0.46 },
      safeZone: { x: 0.69, y: 0.42, width: 0.30, height: 0.57 },
      landmarkAvoidRects: [{ x: 0.08, y: 0.02, width: 0.60, height: 0.78 }],
      groundPolygon: [[0.0, 0.78], [1.0, 0.76], [1.0, 1.0], [0.0, 1.0]],
      lightDirection: 'upper-left',
      lightTemperature: 'warm',
      shadowOpacity: 0.16,
      shadowBlur: 16,
      shadowAngle: 12,
      personSlots: [{ id: 'right', label: 'Sân trống bên phải', x: 0.84 }],
    },
  },
  {
    id: 'okayama-korakuen-lawn',
    spotPlace: 'Vườn Okayama Kōrakuen',
    spotPrefecture: 'Okayama',
    name: 'Bãi cỏ trước hồ cảnh',
    mood: 'Thanh nhã',
    timeOfDay: 'day',
    season: 'all',
    imageFile: 'okayama-korakuen-lawn.jpg',
    thumbnailUrl: '/assets/japan-scenes/okayama-korakuen-lawn-thumb.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Okayama_Korakuen_01.jpg',
    author: 'Zairon',
    license: 'CC BY 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
    attribution: 'Zairon, CC BY 4.0, qua Wikimedia Commons',
    checkedAt: '2026-09-01',
    groundType: 'cỏ',
    wardrobeNote: 'Mảng cỏ sáng và cây tỉa thấp hợp màu đỏ rượu, xanh chàm và họa tiết truyền thống.',
    composition: {
      horizonY: 0.38,
      groundLineY: 0.50,
      footAnchor: { x: 0.18, y: 0.70 },
      personHeightRatio: { min: 0.28, preferred: 0.38, max: 0.45 },
      safeZone: { x: 0.02, y: 0.18, width: 0.34, height: 0.56 },
      landmarkAvoidRects: [{ x: 0.36, y: 0.43, width: 0.60, height: 0.38 }],
      groundPolygon: [[0.0, 0.48], [0.40, 0.48], [0.38, 0.78], [0.0, 0.80]],
      lightDirection: 'upper-left',
      lightTemperature: 'neutral',
      shadowOpacity: 0.18,
      shadowBlur: 18,
      shadowAngle: 16,
      personSlots: [{ id: 'left', label: 'Bãi cỏ bên trái', x: 0.18 }],
    },
  },
  {
    id: 'senganen-sakurajima-lawn',
    spotPlace: 'Vườn Sengan-en',
    spotPrefecture: 'Kagoshima',
    name: 'Bãi cỏ nhìn núi Sakurajima',
    mood: 'Khoáng đạt',
    timeOfDay: 'day',
    season: 'all',
    imageFile: 'senganen-sakurajima-lawn.jpg',
    thumbnailUrl: '/assets/japan-scenes/senganen-sakurajima-lawn-thumb.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Sengan-en_(4549028031).jpg',
    author: 'KimonBerlin',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    attribution: 'KimonBerlin, CC BY-SA 2.0, qua Wikimedia Commons',
    checkedAt: '2026-09-01',
    groundType: 'cỏ',
    wardrobeNote: 'Màu đất, cỏ và núi lam hợp đồ sáng, đỏ son hoặc xanh cổ vịt.',
    composition: {
      horizonY: 0.45,
      groundLineY: 0.55,
      footAnchor: { x: 0.18, y: 0.92 },
      personHeightRatio: { min: 0.34, preferred: 0.48, max: 0.58 },
      safeZone: { x: 0.04, y: 0.37, width: 0.30, height: 0.58 },
      landmarkAvoidRects: [{ x: 0.30, y: 0.18, width: 0.42, height: 0.36 }],
      groundPolygon: [[0.0, 0.56], [0.78, 0.55], [1.0, 1.0], [0.0, 1.0]],
      lightDirection: 'upper-left',
      lightTemperature: 'warm',
      shadowOpacity: 0.19,
      shadowBlur: 18,
      shadowAngle: 10,
      personSlots: [{ id: 'left', label: 'Bãi cỏ trống bên trái', x: 0.18 }],
    },
  },
  {
    id: 'kakunodate-samurai-street',
    spotPlace: 'Phố samurai Kakunodate',
    spotPrefecture: 'Akita',
    name: 'Đường Bukeyashiki mùa lá đỏ',
    mood: 'Hoài cổ',
    timeOfDay: 'day',
    season: 'autumn',
    imageFile: 'kakunodate-samurai-street.jpg',
    thumbnailUrl: '/assets/japan-scenes/kakunodate-samurai-street-thumb.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Bukeyashiki_Street_in_Kakunodate_20161106b.jpg',
    author: '掬茶',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '掬茶, CC BY-SA 4.0, qua Wikimedia Commons',
    checkedAt: '2026-09-01',
    groundType: 'đường nhựa',
    wardrobeNote: 'Lá đỏ và hàng rào đen tạo tương phản đẹp cho kimono kem, xanh chàm hoặc vàng nhạt.',
    composition: {
      horizonY: 0.49,
      groundLineY: 0.61,
      footAnchor: { x: 0.50, y: 0.96 },
      personHeightRatio: { min: 0.38, preferred: 0.54, max: 0.64 },
      safeZone: { x: 0.35, y: 0.35, width: 0.30, height: 0.63 },
      landmarkAvoidRects: [
        { x: 0.0, y: 0.0, width: 0.24, height: 0.65 },
        { x: 0.76, y: 0.0, width: 0.24, height: 0.68 },
      ],
      groundPolygon: [[0.30, 0.60], [0.70, 0.60], [0.92, 1.0], [0.08, 1.0]],
      lightDirection: 'upper-left',
      lightTemperature: 'warm',
      shadowOpacity: 0.23,
      shadowBlur: 15,
      shadowAngle: 18,
      personSlots: [{ id: 'center', label: 'Giữa đường', x: 0.50 }],
    },
  },
  {
    id: 'furano-farm-tomita-path',
    spotPlace: 'Cánh đồng hoa Farm Tomita',
    spotPrefecture: 'Hokkaido',
    name: 'Lối giữa luống oải hương',
    mood: 'Mùa hè',
    timeOfDay: 'day',
    season: 'summer',
    imageFile: 'furano-farm-tomita-path.jpg',
    thumbnailUrl: '/assets/japan-scenes/furano-farm-tomita-path-thumb.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Farm_Tomita_20140812-7.jpg',
    author: 'Suicasmo',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: 'Suicasmo, CC BY-SA 4.0, qua Wikimedia Commons',
    checkedAt: '2026-09-01',
    groundType: 'đường nhựa',
    wardrobeNote: 'Oải hương tím và lá xanh tôn đồ trắng, kem, vàng nhạt và pastel.',
    composition: {
      horizonY: 0.20,
      groundLineY: 0.35,
      footAnchor: { x: 0.53, y: 0.96 },
      personHeightRatio: { min: 0.34, preferred: 0.44, max: 0.52 },
      safeZone: { x: 0.40, y: 0.39, width: 0.26, height: 0.58 },
      landmarkAvoidRects: [
        { x: 0.0, y: 0.28, width: 0.38, height: 0.72 },
        { x: 0.70, y: 0.25, width: 0.30, height: 0.75 },
      ],
      groundPolygon: [[0.44, 0.36], [0.62, 0.36], [0.70, 1.0], [0.36, 1.0]],
      lightDirection: 'upper-left',
      lightTemperature: 'neutral',
      shadowOpacity: 0.17,
      shadowBlur: 15,
      shadowAngle: 12,
      personSlots: [{ id: 'center', label: 'Giữa lối hoa', x: 0.53 }],
    },
  },
  {
    id: 'kanazawa-higashi-chaya-street',
    spotPlace: 'Phố trà Higashi Chaya',
    spotPrefecture: 'Ishikawa',
    name: 'Phố nhà trà lát đá',
    mood: 'Cổ điển',
    timeOfDay: 'day',
    season: 'all',
    imageFile: 'kanazawa-higashi-chaya-street.jpg',
    thumbnailUrl: '/assets/japan-scenes/kanazawa-higashi-chaya-street-thumb.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Higashi_Chaya_district,_Kanazawa_(3810704024).jpg',
    author: 'Andrea Schaffer',
    license: 'CC BY 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.0/',
    attribution: 'Andrea Schaffer, CC BY 2.0, qua Wikimedia Commons',
    checkedAt: '2026-09-01',
    groundType: 'đá lát',
    wardrobeNote: 'Mặt tiền gỗ sẫm là nền tự nhiên cho kimono sáng, họa tiết hoa và phụ kiện đỏ.',
    composition: {
      horizonY: 0.48,
      groundLineY: 0.62,
      footAnchor: { x: 0.50, y: 0.96 },
      personHeightRatio: { min: 0.40, preferred: 0.56, max: 0.66 },
      safeZone: { x: 0.34, y: 0.31, width: 0.32, height: 0.67 },
      landmarkAvoidRects: [
        { x: 0.0, y: 0.0, width: 0.28, height: 0.78 },
        { x: 0.72, y: 0.0, width: 0.28, height: 0.78 },
      ],
      groundPolygon: [[0.30, 0.60], [0.70, 0.60], [0.94, 1.0], [0.06, 1.0]],
      lightDirection: 'front',
      lightTemperature: 'neutral',
      shadowOpacity: 0.20,
      shadowBlur: 14,
      shadowAngle: 0,
      personSlots: [{ id: 'center', label: 'Giữa phố', x: 0.50 }],
    },
  },
  {
    id: 'sapporo-moerenuma-avenue',
    spotPlace: 'Công viên Moerenuma',
    spotPrefecture: 'Hokkaido',
    name: 'Đại lộ xanh Moerenuma',
    mood: 'Hiện đại',
    timeOfDay: 'day',
    season: 'summer',
    imageFile: 'sapporo-moerenuma-avenue.jpg',
    thumbnailUrl: '/assets/japan-scenes/sapporo-moerenuma-avenue-thumb.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Avenue_in_Moerenuma_Park.jpg',
    author: '掬茶',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: '掬茶, CC BY-SA 4.0, qua Wikimedia Commons',
    checkedAt: '2026-09-01',
    groundType: 'đường nhựa',
    wardrobeNote: 'Trời xanh và thảm cỏ tối giản hợp outfit phố hiện đại, blazer và đồ trắng.',
    composition: {
      horizonY: 0.46,
      groundLineY: 0.58,
      footAnchor: { x: 0.38, y: 0.96 },
      personHeightRatio: { min: 0.30, preferred: 0.40, max: 0.48 },
      safeZone: { x: 0.25, y: 0.42, width: 0.26, height: 0.55 },
      landmarkAvoidRects: [{ x: 0.76, y: 0.43, width: 0.24, height: 0.57 }],
      // Chỉ mặt đường phẳng; loại hẳn sườn cỏ bên phải dù về ngữ nghĩa vẫn là
      // "mặt đất", vì chân người thẳng đứng trên dốc nhìn như đang lơ lửng.
      groundPolygon: [[0.10, 0.93], [0.61, 0.82], [0.71, 0.88], [0.58, 1.0], [0.08, 1.0]],
      lightDirection: 'upper-left',
      lightTemperature: 'neutral',
      shadowOpacity: 0.20,
      shadowBlur: 18,
      shadowAngle: 16,
      personSlots: [{ id: 'road', label: 'Mặt đường phẳng phía trước', x: 0.38 }],
    },
  },
  {
    id: 'ashikaga-wisteria-path',
    spotPlace: 'Công viên hoa Ashikaga',
    spotPrefecture: 'Tochigi',
    name: 'Lối đi bên giàn tử đằng',
    mood: 'Lãng mạn',
    timeOfDay: 'day',
    season: 'spring',
    imageFile: 'ashikaga-wisteria-path.jpg',
    thumbnailUrl: '/assets/japan-scenes/ashikaga-wisteria-path-thumb.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Japanese_wisteria,_Ashikaga_Flower_Park_14.jpg',
    author: 'SLIMHANNYA',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: 'SLIMHANNYA, CC BY-SA 4.0, qua Wikimedia Commons',
    checkedAt: '2026-09-01',
    groundType: 'đá lát',
    wardrobeNote: 'Hoa tím và trắng hợp váy đơn sắc, yukata pastel và trang phục sáng màu.',
    composition: {
      horizonY: 0.38,
      groundLineY: 0.58,
      footAnchor: { x: 0.22, y: 0.95 },
      personHeightRatio: { min: 0.34, preferred: 0.46, max: 0.56 },
      safeZone: { x: 0.04, y: 0.39, width: 0.32, height: 0.58 },
      landmarkAvoidRects: [{ x: 0.42, y: 0.18, width: 0.54, height: 0.62 }],
      groundPolygon: [[0.0, 0.58], [0.39, 0.54], [0.42, 1.0], [0.0, 1.0]],
      lightDirection: 'upper-left',
      lightTemperature: 'neutral',
      shadowOpacity: 0.18,
      shadowBlur: 16,
      shadowAngle: 14,
      personSlots: [{ id: 'left', label: 'Lối đi bên trái', x: 0.22 }],
    },
  },
  {
    id: 'tokyo-shinjuku-gyoen-lawn',
    spotPlace: 'Vườn Shinjuku Gyoen',
    spotPrefecture: 'Tokyo',
    name: 'Thảm cỏ nhìn tháp NTT Docomo',
    mood: 'Xanh giữa phố',
    timeOfDay: 'day',
    season: 'all',
    imageFile: 'tokyo-shinjuku-gyoen-lawn.jpg',
    thumbnailUrl: '/assets/japan-scenes/tokyo-shinjuku-gyoen-lawn-thumb.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Shinjuku_Gyoen_National_Garden_and_NTT_DoCoMo_Yoyogi_Building,_Tokyo,_Japan.jpg',
    author: 'Basile Morin',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution: 'Basile Morin, CC BY-SA 4.0, qua Wikimedia Commons',
    checkedAt: '2026-09-01',
    groundType: 'cỏ',
    wardrobeNote: 'Thảm cỏ sáng và đường chân trời Tokyo hợp cả kimono lẫn outfit phố tối giản.',
    composition: {
      horizonY: 0.38,
      groundLineY: 0.52,
      footAnchor: { x: 0.35, y: 0.94 },
      personHeightRatio: { min: 0.34, preferred: 0.48, max: 0.58 },
      safeZone: { x: 0.18, y: 0.39, width: 0.34, height: 0.58 },
      landmarkAvoidRects: [{ x: 0.54, y: 0.04, width: 0.18, height: 0.38 }],
      groundPolygon: [[0.0, 0.50], [1.0, 0.48], [1.0, 1.0], [0.0, 1.0]],
      lightDirection: 'upper-left',
      lightTemperature: 'neutral',
      shadowOpacity: 0.18,
      shadowBlur: 18,
      shadowAngle: 15,
      personSlots: [{ id: 'left', label: 'Thảm cỏ trống bên trái', x: 0.35 }],
    },
  },
  ...CATALOG_COVERAGE_SCENES,
]);

const BY_ID = new Map(SCENES.map((scene) => [scene.id, scene]));

function spotKey(place, prefecture) {
  return `${String(place || '').trim()}::${String(prefecture || '').trim()}`;
}

const BY_SPOT = new Map();
for (const scene of SCENES) {
  const key = spotKey(scene.spotPlace, scene.spotPrefecture);
  if (!BY_SPOT.has(key)) BY_SPOT.set(key, []);
  BY_SPOT.get(key).push(scene);
}

/** Thông tin scene an toàn để trả cho app: không có toạ độ nội bộ nào bị giấu. */
function publicScene(scene) {
  const { composition, imageFile, ...rest } = scene;
  return {
    ...rest,
    // App cần biết vị trí đặt người để vẽ hình bóng mờ lên thumbnail.
    footAnchor: composition.footAnchor,
    personHeightRatio: composition.personHeightRatio,
    safeZone: composition.safeZone,
    personSlots: composition.personSlots,
    recommendedPoseId: recommendedTravelPose(scene),
    poseOptions: publicTravelPoses(scene),
  };
}

function scenesForSpot(place, prefecture) {
  return (BY_SPOT.get(spotKey(place, prefecture)) || []).map(publicScene);
}

/** Đường dẫn đĩa của ảnh nền. Chỉ dùng trong tiến trình backend. */
function sceneImagePath(scene) {
  return path.join(SCENE_DIR, scene.imageFile);
}

function findScene(id) {
  return BY_ID.get(String(id || '').trim()) || null;
}

/** Địa điểm nào đã có góc chụp được duyệt. */
function spotsWithScenes() {
  return [...BY_SPOT.keys()].map((key) => {
    const [place, prefecture] = key.split('::');
    return { place, prefecture, sceneCount: BY_SPOT.get(key).length };
  });
}

module.exports = { SCENES, SCENE_DIR, sceneImagePath, publicScene, scenesForSpot, findScene, spotsWithScenes, spotKey };
