export type PhotoSpot = { name: string; tip: string };
export type JapanSpot = {
  place: string; photoUrl: string; prefecture: string; time: string; tip: string; slug: string; where: string; history: string;
  highlights: string[]; photoSpots: PhotoSpot[]; access: string; mapQuery: string; sourceLabel: string; sourceUrl: string;
};
// Ảnh thật từ Wikimedia Commons (Creative Commons) — chỉ dùng ảnh của đúng địa
// điểm, không dùng ảnh sản phẩm quần áo để tránh gây hiểu lầm đây là ảnh du lịch thật.
export const PHOTO_ATTRIBUTION = 'Ảnh: Wikimedia Commons (Creative Commons)';

// Video giới thiệu chính thức theo tỉnh (kênh du lịch/chính quyền địa phương trên YouTube).
export const PREFECTURE_VIDEO: Record<string, string> = {
  'Kyoto': 'FLsncmk6YNQ',
  'Nara': '9cvC2Mn4Rz4',
  'Osaka': 'CXYpmupXFIw',
  'Tokyo': 'TNomzoYXWMc',
  'Ibaraki': 'gPBBemKwgUs',
  'Kanagawa': 'p7lp6n1UeNw',
  'Yamanashi': 'OcLSaTysZmg',
  'Gifu': 'zzJXE3m-WGY',
  'Ishikawa': 'xXwJ8QzSFOs',
  'Nagano': '54xamR-8gRk',
  'Hokkaido': 'DBfJB7h-vKs',
  'Aomori': 'xBgc8A5BEWg',
  'Hiroshima': '8jtlvO7Yd7E',
  'Ehime': 'BrCJV3_PG5k',
  'Okinawa': 'a_PdyNmGWSo',
  'Oita': 'IjdQmpOlujo',
};

// Vùng địa lý thật của Nhật Bản, chỉ liệt kê những vùng có ít nhất một địa
// điểm trong SPOTS bên dưới để tránh mục trống.
export const REGION_OF_PREFECTURE: Record<string, string> = {
  'Kyoto': 'Kansai',
  'Nara': 'Kansai',
  'Osaka': 'Kansai',
  'Tokyo': 'Kantō',
  'Ibaraki': 'Kantō',
  'Kanagawa': 'Kantō',
  'Yamanashi': 'Chūbu',
  'Gifu': 'Chūbu',
  'Ishikawa': 'Chūbu',
  'Nagano': 'Chūbu',
  'Hokkaido': 'Hokkaido',
  'Aomori': 'Tōhoku',
  'Hiroshima': 'Chūgoku',
  'Yamaguchi': 'Chūgoku',
  'Ehime': 'Shikoku',
  'Okinawa': 'Kyūshū & Okinawa',
  'Oita': 'Kyūshū & Okinawa',
  'Kagawa': 'Shikoku',
  'Wakayama': 'Kansai',
  'Okayama': 'Chūgoku',
  'Miyazaki': 'Kyūshū & Okinawa',
  'Yamagata': 'Tōhoku',
  'Hyogo': 'Kansai',
  'Kagoshima': 'Kyūshū & Okinawa',
  'Akita': 'Tōhoku',
  'Tochigi': 'Kantō',
};

export const SPOTS: JapanSpot[] = [
  { place: 'Rừng tre Arashiyama', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Bamboo_Grove%2C_Arashiyama%2C_Kyoto%2C_Japan.jpg/960px-Bamboo_Grove%2C_Arashiyama%2C_Kyoto%2C_Japan.jpg', prefecture: 'Kyoto', time: 'Sáng sớm · 07:00–09:00', tip: 'Lối tre xanh tạo chiều sâu rất đẹp cho ảnh toàn thân.', slug: 'kimono-hong', where: 'Khu Sagano, quận Ukyō, phía tây Kyoto; gần chùa Tenryū-ji và ga Arashiyama.', history: 'Rừng tre nằm trong vùng thắng cảnh Arashiyama–Sagano, nơi giới quý tộc thời Heian từng đến thưởng ngoạn. Tre cũng gắn với thủ công và kiến trúc truyền thống Kyoto.', highlights: ['Lối tre cao khép vòm, tiếng lá và ánh sáng lọc tạo không gian rất đặc trưng.', 'Có thể nối tuyến đi bộ với Tenryū-ji, cầu Togetsukyō và khu Sagano.'], photoSpots: [{ name: 'Lối tre chính', tip: 'Đứng lệch tâm, dùng đường mòn làm đường dẫn; đến sớm để nền ít người.' }, { name: 'Nonomiya-jinja', tip: 'Cổng torii đen và rêu xanh hợp ảnh bán thân, trang phục truyền thống.' }, { name: 'Cầu Togetsukyō', tip: 'Lấy cầu, sông Katsura và sườn núi thành ba lớp hậu cảnh.' }], access: 'Từ ga JR Saga-Arashiyama đi bộ khoảng 10–15 phút.', mapQuery: 'Arashiyama Bamboo Forest Kyoto', sourceLabel: 'Kyoto City Official Travel Guide', sourceUrl: 'https://kyoto.travel/en/other_attractions/119.html' },
  { place: 'Đền Fushimi Inari', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Torii_path_with_lantern_at_Fushimi_Inari_Taisha_Shrine%2C_Kyoto%2C_Japan.jpg/960px-Torii_path_with_lantern_at_Fushimi_Inari_Taisha_Shrine%2C_Kyoto%2C_Japan.jpg', prefecture: 'Kyoto', time: 'Sáng sớm · trước 08:00', tip: 'Hàng nghìn cổng torii đỏ hợp trang phục truyền thống.', slug: 'yukata-xanh', where: 'Quận Fushimi, phía nam Kyoto, ngay cạnh ga JR Inari; lối hành hương kéo dài lên núi Inari.', history: 'Đền có nguồn gốc từ thế kỷ VIII và là trung tâm thờ Inari, vị thần gắn với lúa gạo rồi mở rộng thành biểu tượng của thịnh vượng và kinh doanh.', highlights: ['Senbon Torii tạo hành lang cổng son dày đặc lên sườn núi.', 'Tượng cáo kitsune là sứ giả của Inari; toàn bộ vòng núi cần khoảng 2–3 giờ.'], photoSpots: [{ name: 'Senbon Torii', tip: 'Chụp lệch tâm ở đoạn cổng dày để tăng chiều sâu.' }, { name: 'Rōmon Gate', tip: 'Góc chính diện cân xứng đẹp nhất vào sáng sớm.' }, { name: 'Yotsutsuji', tip: 'Đi cao hơn để lấy toàn cảnh phía nam Kyoto.' }], access: 'JR Nara Line đến ga Inari; đền ở ngay phía trước ga.', mapQuery: 'Fushimi Inari Taisha Kyoto', sourceLabel: 'Kyoto City Official Travel Guide', sourceUrl: 'https://kyoto.travel/en/destinations/fushimi-inaritaisha-shrine/' },
  { place: 'Phố cổ Gion', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/150124_Gion_Kyoto_Japan01s3.jpg/960px-150124_Gion_Kyoto_Japan01s3.jpg', prefecture: 'Kyoto', time: 'Chiều vàng · 16:30–18:00', tip: 'Nhà machiya và ngõ lát đá cho khung hình Nhật cổ.', slug: 'haori-dang-dai', where: 'Bờ đông sông Kamo, quanh đại lộ Shijō, Hanamikoji và khu Shirakawa của Kyoto.', history: 'Gion phát triển từ khu phục vụ người hành hương đến Yasaka-jinja; về sau nổi tiếng với các ochaya và văn hóa biểu diễn của geiko, maiko.', highlights: ['Nhà machiya gỗ, rèm noren và đèn lồng tạo cảnh quan đô thị cổ.', 'Đây vẫn là khu dân cư và làm việc; cần tránh chụp người khi chưa xin phép.'], photoSpots: [{ name: 'Gion Shirakawa', tip: 'Chụp bên kênh, cầu Tatsumi và hàng liễu lúc chiều vàng.' }, { name: 'Hanamikoji', tip: 'Lấy mặt tiền machiya; đứng ở khu vực công cộng và không cản lối.' }, { name: 'Yasaka-jinja', tip: 'Cổng son và đèn lồng đẹp khi chuyển từ chiều sang tối.' }], access: 'Đi bộ từ ga Gion-Shijō hoặc trạm xe buýt Gion.', mapQuery: 'Gion Shirakawa Kyoto', sourceLabel: 'Kyoto City Official Travel Guide', sourceUrl: 'https://kyoto.travel/en/see-and-do/gion.html' },
  { place: 'Hồ Kawaguchi', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/KawaguchiKo.jpg/960px-KawaguchiKo.jpg', prefecture: 'Yamanashi', time: 'Bình minh · trời quang', tip: 'Chụp cùng núi Phú Sĩ và mặt hồ phản chiếu.', slug: 'cardigan-dai', where: 'Thị trấn Fujikawaguchiko, tỉnh Yamanashi, phía bắc núi Phú Sĩ; thuộc vùng Ngũ Hồ Phú Sĩ.', history: 'Kawaguchi là hồ dễ tiếp cận nhất trong Ngũ Hồ và trở thành điểm ngắm Phú Sĩ tiêu biểu nhờ bờ bắc mở rộng, cảnh quan thay đổi rõ theo mùa.', highlights: ['Mặt hồ cho ảnh phản chiếu Phú Sĩ khi trời trong và ít gió.', 'Bờ bắc nổi bật với hoa anh đào, oải hương và lá đỏ theo mùa.'], photoSpots: [{ name: 'Công viên Oishi', tip: 'Dùng dải hoa tiền cảnh, hồ ở trung cảnh và Phú Sĩ phía sau.' }, { name: 'Bờ bắc Ubuyagasaki', tip: 'Sáng sớm dễ có phản chiếu và ánh sáng mềm.' }, { name: 'Cầu Kawaguchiko-ohashi', tip: 'Chọn điểm ven bờ để lấy cầu dẫn mắt về phía núi.' }], access: 'Xe buýt từ ga Kawaguchiko chạy vòng hồ; Oishi nằm trên tuyến Red Line.', mapQuery: 'Lake Kawaguchi Oishi Park', sourceLabel: 'Fujikawaguchiko Tourism', sourceUrl: 'https://fujisan.ne.jp/en/' },
  { place: 'Công viên Nara', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Nara_Park_-_panoramio_%282%29.jpg/960px-Nara_Park_-_panoramio_%282%29.jpg', prefecture: 'Nara', time: 'Sáng · 08:00–10:00', tip: 'Ánh sáng mềm, bãi cỏ rộng và những chú hươu thân thiện.', slug: 'kimono-hong', where: 'Trung tâm Nara, trải từ khu Kōfuku-ji qua bảo tàng đến Tōdai-ji và chân núi Wakakusa.', history: 'Không gian công viên hình thành quanh các đền chùa cổ của cố đô Nara. Hươu được tôn trọng lâu đời như sứ giả thần linh của Kasuga Taisha.', highlights: ['Hươu đi lại tự do giữa bãi cỏ và các di tích lịch sử.', 'Có thể kết hợp Tōdai-ji, Kasuga Taisha và núi Wakakusa trong một tuyến đi bộ.'], photoSpots: [{ name: 'Ukimidō', tip: 'Chụp nhà thủy tạ phản chiếu trên ao Sagiike vào sáng sớm.' }, { name: 'Đường vào Kasuga Taisha', tip: 'Đèn đá phủ rêu tạo nhịp ảnh sâu trong rừng.' }, { name: 'Chân núi Wakakusa', tip: 'Bãi cỏ rộng cho ảnh cùng hươu; giữ khoảng cách và không trêu chúng.' }], access: 'Khoảng 5 phút đi bộ từ ga Kintetsu Nara.', mapQuery: 'Nara Park Ukimido', sourceLabel: 'Nara Park official guide', sourceUrl: 'https://www3.pref.nara.jp/park/' },
  { place: 'Đài quan sát Shibuya', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/SHIBUYA_SCRAMBLE_SQUARE_East_Tower.jpg/960px-SHIBUYA_SCRAMBLE_SQUARE_East_Tower.jpg', prefecture: 'Tokyo', time: 'Hoàng hôn · đặt giờ trước', tip: 'Đường chân trời Tokyo hợp với bộ trang phục hiện đại, sắc nét.', slug: 'blazer-kaki', where: 'SHIBUYA SKY trên nóc Shibuya Scramble Square, nối trực tiếp với ga Shibuya, Tokyo.', history: 'Đài quan sát mở năm 2019 trong dự án tái phát triển Shibuya, đưa góc nhìn 360° lên một trong những nút giao biểu tượng của Tokyo.', highlights: ['Sân thượng mở nhìn thấy giao lộ Shibuya, Tokyo Tower và xa hơn khi trời quang.', 'Vé theo khung giờ; vật dụng rời bị hạn chế trên sân thượng vì gió.'], photoSpots: [{ name: 'Sky Edge', tip: 'Góc kính sát biên tạo cảm giác thành phố mở rộng phía dưới.' }, { name: 'Crossing View', tip: 'Chụp giao lộ từ trên cao sau khi đèn đường bật.' }, { name: 'Cloud Hammock', tip: 'Ảnh hướng lên trời đẹp lúc chuyển màu hoàng hôn.' }], access: 'Lối vào tầng 14 Shibuya Scramble Square; nên đặt vé giờ hoàng hôn trước.', mapQuery: 'SHIBUYA SKY', sourceLabel: 'SHIBUYA SKY official', sourceUrl: 'https://www.shibuya-scramble-square.com/sky/' },
  { place: 'Omoide Yokocho', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Entrance_to_Omoide_Yokocho.jpg/960px-Entrance_to_Omoide_Yokocho.jpg', prefecture: 'Tokyo', time: 'Tối · sau 19:00', tip: 'Đèn lồng và biển hiệu nhỏ tạo chất điện ảnh đường phố.', slug: 'dong-phuc-thuy-thu', where: 'Cửa tây ga Shinjuku, Tokyo; mê cung ngõ nhỏ nằm sát đường ray và khu phố thương mại.', history: 'Khu quán bắt đầu từ chợ đen sau Thế chiến II, rồi phát triển thành dãy quán yakitori và izakaya nhỏ mang diện mạo Shōwa.', highlights: ['Ngõ rất hẹp, khói bếp và đèn lồng cho không khí điện ảnh.', 'Không gian kinh doanh thực; cần hỏi trước khi chụp cận quán hoặc khách.'], photoSpots: [{ name: 'Lối vào phía nam', tip: 'Lấy biển hiệu và đường ngõ hội tụ; dùng tiêu cự vừa để không chắn lối.' }, { name: 'Ngõ đèn lồng', tip: 'Đo sáng theo vùng sáng để giữ màu đèn và khói bếp.' }, { name: 'Cửa quán yakitori', tip: 'Xin phép trước, ưu tiên ảnh chi tiết thay vì chụp mặt khách.' }], access: 'Khoảng 2 phút đi bộ từ cửa Tây ga JR Shinjuku.', mapQuery: 'Omoide Yokocho Shinjuku', sourceLabel: 'GO TOKYO official guide', sourceUrl: 'https://www.gotokyo.org/en/spot/73/index.html' },
  { place: 'Kênh Otaru', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Otaru_Canal_HDR1.jpg/960px-Otaru_Canal_HDR1.jpg', prefecture: 'Hokkaido', time: 'Chạng vạng · trước khi đèn sáng', tip: 'Kho đá, đèn vàng và tuyết tạo nền ảnh rất lãng mạn.', slug: 'ao-len-co-lo', where: 'Trung tâm thành phố cảng Otaru, Hokkaido, cách ga JR Otaru khoảng 10 phút đi bộ.', history: 'Kênh hoàn thành đầu thế kỷ XX để chuyển hàng từ tàu lớn vào kho ven bờ. Khi cảng hiện đại hóa, một phần kênh được bảo tồn thành phố đi bộ.', highlights: ['Kho gạch đá phản chiếu trên nước và đèn khí tạo nét cảng cổ.', 'Mùa đông có tuyết, nhưng mặt đường trơn; chạng vạng cân bằng được trời xanh và đèn vàng.'], photoSpots: [{ name: 'Asakusa Bridge', tip: 'Góc kinh điển lấy đường cong kênh và dãy kho.' }, { name: 'Lối đi bờ đông', tip: 'Dùng đèn khí làm nhịp dẫn dọc khung hình.' }, { name: 'Kho Otaru phía nam', tip: 'Chụp chi tiết tường đá và tuyết để tạo chất cổ điển.' }], access: 'Đi thẳng từ ga JR Otaru theo Chūō-dōri khoảng 10 phút.', mapQuery: 'Otaru Canal Asakusa Bridge', sourceLabel: 'Otaru Tourism Association', sourceUrl: 'https://www.visit-otaru-en.info/' },
  { place: 'Làng Shirakawa-go', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Ogi_Shirakawa-g%C5%8D%2C_Gifu%2C_Japan.jpg/960px-Ogi_Shirakawa-g%C5%8D%2C_Gifu%2C_Japan.jpg', prefecture: 'Gifu', time: 'Sáng sớm · đẹp quanh năm', tip: 'Nhà mái tranh gasshō-zukuri và thung lũng sông Shō tạo nhiều lớp ảnh.', slug: 'khoac-nhat', where: 'Làng Ogimachi, xã Shirakawa, quận Ōno, phía tây bắc tỉnh Gifu; nằm trong thung lũng sông Shō giữa vùng núi Chūbu.', history: 'Vùng núi từng biệt lập lâu dài, cư dân trồng dâu và nuôi tằm trong các nhà lớn. Mái tranh dốc thích nghi với tuyết dày; Ogimachi cùng Ainokura và Suganuma được UNESCO ghi danh năm 1995.', highlights: ['"Gasshō" nghĩa là hai bàn tay chắp lại; mái dốc tạo khoảng áp mái lớn dùng cho nghề tằm.', 'Tinh thần "Yui" là việc cộng đồng chia sẻ lao động, rõ nhất khi cùng thay mái tranh. Hơn 100 công trình gasshō lớn nhỏ vẫn nằm trong một ngôi làng có người sinh sống.'], photoSpots: [{ name: 'Đài quan sát Shiroyama', tip: 'Góc toàn cảnh tốt nhất: làng ở tiền cảnh, sông và núi ôm phía sau. Có đường đi bộ hoặc shuttle ban ngày.' }, { name: 'Nhà Wada', tip: 'Chụp từ đường công cộng để lấy hàng rào, ruộng và mái tranh nhiều lớp; bên trong kể lịch sử nghề tằm.' }, { name: 'Cầu Deai-bashi', tip: 'Dùng cầu treo làm đường dẫn khi bước từ bãi Seseragi vào làng; sáng sớm ánh sáng dịu.' }, { name: 'Các ngõ Ogimachi', tip: 'Tìm kênh nước và ruộng làm tiền cảnh; không bước vào sân nhà dân hoặc dùng drone.' }], access: 'Không có ga tàu. Xe buýt cao tốc: khoảng 50 phút từ Takayama hoặc 1 giờ 20 phút từ Kanazawa/Toyama; nên dành 2–3 giờ đi bộ.', mapQuery: 'Shirakawa-go Ogimachi Gifu', sourceLabel: 'UNESCO & Hiệp hội Du lịch Shirakawa-go', sourceUrl: 'https://shirakawa-go.gr.jp/en/highlights/' },
  { place: 'Công viên Hitachi Seaside', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/2025_Hitachi_Seaside_Park_2.jpg/960px-2025_Hitachi_Seaside_Park_2.jpg', prefecture: 'Ibaraki', time: 'Sáng ngày nắng nhẹ', tip: 'Đồi hoa theo mùa tạo mảng màu rộng và trong trẻo.', slug: 'yae-miko', where: 'Thành phố Hitachinaka, tỉnh Ibaraki, ven Thái Bình Dương và cách Tokyo khoảng hai giờ.', history: 'Khu đất được phát triển thành công viên quốc gia quy mô lớn; cảnh quan nổi tiếng nhờ các cánh đồng hoa được chăm theo mùa trên đồi Miharashi.', highlights: ['Nemophila xanh vào mùa xuân và kochia chuyển đỏ vào mùa thu là hai cảnh quan biểu tượng.', 'Công viên rất rộng, có tuyến xe và xe đạp; lịch hoa thay đổi theo thời tiết từng năm.'], photoSpots: [{ name: 'Miharashi Hill', tip: 'Chụp từ sườn thấp để hoa phủ kín nền và giữ đường chân trời sạch.' }, { name: 'Đường lên đồi', tip: 'Dùng lối cong làm đường dẫn, tránh bước vào luống hoa.' }, { name: 'Dune Garden', tip: 'Cỏ biển và ánh sáng ven bờ hợp ảnh tối giản, ít đông hơn đồi chính.' }], access: 'Từ ga Katsuta đi xe buýt đến cổng Tây hoặc cổng Kaihin; kiểm tra lịch hoa trước chuyến đi.', mapQuery: 'Hitachi Seaside Park Miharashi Hill', sourceLabel: 'Hitachi Seaside Park official', sourceUrl: 'https://hitachikaihin.jp/en/' },
  { place: 'Lâu đài Osaka', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Osaka_Castle_03bs3200.jpg/960px-Osaka_Castle_03bs3200.jpg', prefecture: 'Osaka', time: 'Sáng · mùa hoa anh đào', tip: 'Tường đá lớn và tháp lâu đài hợp trang phục truyền thống hoặc vest gọn.', slug: 'blazer-kaki', where: 'Công viên lâu đài Osaka, quận Chūō, trung tâm thành phố Osaka.', history: 'Xây năm 1583 bởi Toyotomi Hideyoshi sau khi thống nhất Nhật Bản, từng là lâu đài lớn nhất thời đó. Bị phá huỷ và tái thiết nhiều lần qua các cuộc chiến; tháp chính hiện tại dựng lại bằng bê tông năm 1931, nay là bảo tàng.', highlights: ['Tường đá khổng lồ ghép từ các phiến đá nguyên khối là điểm nổi bật kỹ thuật thời Edo.', 'Vườn Nishinomaru trong khuôn viên có hàng trăm cây anh đào, đẹp nhất cuối tháng 3–đầu tháng 4.'], photoSpots: [{ name: 'Cầu Gokurakubashi', tip: 'Lấy tháp lâu đài phía sau hào nước làm hậu cảnh cân xứng.' }, { name: 'Vườn Nishinomaru', tip: 'Mùa hoa nên đến sớm để có nền hoa sạch, ít người qua lại.' }, { name: 'Chân tường đá', tip: 'Đứng gần để thấy rõ tỉ lệ phiến đá khổng lồ, tạo chiều sâu ảnh.' }], access: 'Đi bộ khoảng 10 phút từ ga Osakajokoen (JR) hoặc ga Tanimachi 4-chōme (Metro).', mapQuery: 'Osaka Castle', sourceLabel: 'Osaka Castle official', sourceUrl: 'https://www.osakacastle.net/foreign/english/' },
  { place: 'Đền Itsukushima · Miyajima', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Itsukushima_Shrine_Torii_Gate_%2813890465459%29.jpg/960px-Itsukushima_Shrine_Torii_Gate_%2813890465459%29.jpg', prefecture: 'Hiroshima', time: 'Nước triều lên · chiều', tip: 'Cổng torii nổi trên biển là khung hình biểu tượng của cả nước Nhật.', slug: 'kimono-hong', where: 'Đảo Miyajima (Itsukushima), vịnh Hiroshima, cách trung tâm thành phố Hiroshima khoảng 30–45 phút.', history: 'Đền có gốc từ thế kỷ VI, kiến trúc hiện tại xây trên mặt nước từ thế kỷ XII dưới sự bảo trợ của lãnh chúa Taira no Kiyomori. Được UNESCO công nhận Di sản Thế giới năm 1996.', highlights: ['Khi triều lên, cổng torii và đền như nổi trên mặt biển; khi triều xuống có thể đi bộ ra tận chân cổng.', 'Đảo còn nổi tiếng với đàn hươu hoang dã đi lại tự do quanh khu đền và núi Misen phía sau.'], photoSpots: [{ name: 'Bờ biển đối diện torii', tip: 'Canh giờ triều lên để có ảnh cổng phản chiếu trên nước.' }, { name: 'Hành lang đền', tip: 'Dùng cột sơn son và mái ngói làm khung dẫn mắt ra biển.' }, { name: 'Chân cổng lúc triều xuống', tip: 'Có thể đi bộ gần cổng; kiểm tra giờ nước ròng trước khi đi.' }], access: 'Tàu JR đến ga Miyajimaguchi rồi đi phà khoảng 10 phút ra đảo.', mapQuery: 'Itsukushima Shrine Miyajima', sourceLabel: 'Miyajima Tourist Association', sourceUrl: 'https://www.miyajima.or.jp/english/' },
  { place: 'Vườn Kenrokuen', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Stone_lantern_Kenrokuen.jpg/960px-Stone_lantern_Kenrokuen.jpg', prefecture: 'Ishikawa', time: 'Sáng sớm · mùa tuyết đẹp nhất', tip: 'Cây thông có giàn yukitsuri chống tuyết tạo hình rất đặc trưng vào mùa đông.', slug: 'cardigan-dai', where: 'Trung tâm thành phố Kanazawa, tỉnh Ishikawa, cạnh lâu đài Kanazawa.', history: 'Một trong "tam đại danh viên" của Nhật Bản cùng Kairakuen và Kōrakuen; gia tộc Maeda, lãnh chúa vùng Kaga, xây dựng và mở rộng suốt gần 200 năm từ thế kỷ XVII. Tên vườn mang nghĩa "khu vườn hội đủ sáu đức tính" theo lý thuyết vườn cảnh Trung Hoa cổ.', highlights: ['Yukitsuri — giàn dây hình nón chống tuyết đè gãy cành thông — trở thành hình ảnh đặc trưng mùa đông Kanazawa.', 'Vườn có ao, suối nhân tạo và đèn đá cổ; cảnh sắc đổi rõ theo bốn mùa.'], photoSpots: [{ name: 'Đèn đá Kotoji-tōrō', tip: 'Biểu tượng của vườn; chụp cạnh mặt hồ Kasumigaike lúc sáng sớm ít người.' }, { name: 'Thông Karasaki', tip: 'Cây thông cổ với giàn yukitsuri lớn nhất vườn vào mùa đông.' }, { name: 'Cầu Gankōbashi', tip: 'Cầu đá hình cánh nhạn, lấy mặt nước làm tiền cảnh.' }], access: 'Xe buýt khoảng 15–20 phút từ ga Kanazawa, xuống trạm Kenrokuen-shita.', mapQuery: 'Kenrokuen Garden Kanazawa', sourceLabel: 'Ishikawa Prefecture official', sourceUrl: 'https://www.pref.ishikawa.jp/siro-niwa/kenrokuen/e/' },
  { place: 'Công viên khỉ tuyết Jigokudani', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Jigokudani_Hotspring_Gorakuen.JPG/960px-Jigokudani_Hotspring_Gorakuen.JPG', prefecture: 'Nagano', time: 'Mùa đông · trời tuyết', tip: 'Khỉ Nhật ngâm mình trong suối nước nóng giữa tuyết trắng — cảnh hiếm có.', slug: 'ao-len-co-lo', where: 'Thị trấn Yamanouchi, tỉnh Nagano, trong thung lũng núi vùng Shiga Kogen.', history: 'Công viên mở cửa năm 1964 để bảo tồn đàn khỉ Nhật Bản hoang dã; đàn khỉ bắt đầu tự xuống tắm trong suối nước nóng của con người từ thập niên 1970, tạo nên hình ảnh nổi tiếng khắp thế giới.', highlights: ['Đây là nơi duy nhất trên thế giới có thể quan sát khỉ hoang dã tắm suối nước nóng ở cự ly gần.', 'Khỉ hoạt động quanh năm nhưng cảnh tuyết mùa đông (tháng 12–3) được xem là đẹp và đặc trưng nhất.'], photoSpots: [{ name: 'Suối nước nóng chính', tip: 'Giữ khoảng cách an toàn, dùng ống kính tele để không làm phiền khỉ.' }, { name: 'Lối đi rừng tuyết', tip: 'Đường mòn phủ tuyết vào công viên cũng là khung hình đẹp.' }], access: 'Từ ga Yudanaka đi xe buýt hoặc taxi khoảng 15 phút, sau đó đi bộ rừng khoảng 30 phút.', mapQuery: 'Jigokudani Monkey Park Nagano', sourceLabel: 'Jigokudani Yaen-koen official', sourceUrl: 'https://jigokudani-yaenkoen.co.jp/' },
  { place: 'Tượng Đại Phật Kamakura', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/230128_Kamakura_Daibutsu_Japan04s3.jpg/960px-230128_Kamakura_Daibutsu_Japan04s3.jpg', prefecture: 'Kanagawa', time: 'Sáng · trời quang', tip: 'Tượng đồng khổng lồ ngoài trời, hợp trang phục trầm và tối giản.', slug: 'so-mi-trang', where: 'Chùa Kōtoku-in, thành phố Kamakura, tỉnh Kanagawa, phía nam Tokyo.', history: 'Tượng Phật A Di Đà bằng đồng cao khoảng 13,35m, đúc năm 1252 thời Kamakura. Điện gỗ che tượng từng bị bão và sóng thần cuốn trôi vào thế kỷ XV; từ đó tượng đứng lộ thiên đến nay.', highlights: ['Là một trong những tượng Phật đồng lớn nhất Nhật Bản còn nguyên vẹn.', 'Có thể vào bên trong thân tượng rỗng để xem cấu trúc đúc đồng cổ.'], photoSpots: [{ name: 'Chính diện tượng', tip: 'Đứng lùi xa để lấy trọn tượng và nền trời; sáng sớm ít khách hơn.' }, { name: 'Góc nghiêng sân chùa', tip: 'Lấy mái chùa nhỏ và cây xanh làm tiền cảnh hai bên tượng.' }], access: 'Từ ga Kamakura đi tàu điện Enoden đến ga Hase, rồi đi bộ khoảng 7 phút.', mapQuery: 'Kotoku-in Great Buddha Kamakura', sourceLabel: 'Kōtoku-in official', sourceUrl: 'https://www.kotoku-in.jp/en/' },
  { place: 'Công viên Ōdōri', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Hokkaido_Sapporo_Odori_Park.jpg/960px-Hokkaido_Sapporo_Odori_Park.jpg', prefecture: 'Hokkaido', time: 'Tháng 2 · lễ hội tuyết', tip: 'Tượng băng tuyết khổng lồ về đêm lên đèn rất lộng lẫy.', slug: 'khoac-nhat', where: 'Dải công viên trung tâm chia đôi thành phố Sapporo, tỉnh Hokkaido.', history: 'Công viên hình thành từ quy hoạch thành phố năm 1871 như một dải đất trống ngăn cháy lan; về sau trở thành không gian công cộng trung tâm và là nơi tổ chức Lễ hội Tuyết Sapporo mỗi tháng 2 từ năm 1950.', highlights: ['Lễ hội Tuyết quy tụ hàng chục tượng băng và tuyết khổng lồ dọc công viên, chiếu sáng nghệ thuật về đêm.', 'Mùa hè công viên chuyển thành nơi tổ chức lễ hội bia và hoa, không khí hoàn toàn khác mùa đông.'], photoSpots: [{ name: 'Khu tượng tuyết lớn', tip: 'Chụp ban đêm khi đèn chiếu lên, dùng tượng làm hậu cảnh chính.' }, { name: 'Tháp truyền hình Sapporo', tip: 'Lên đài quan sát để lấy toàn cảnh công viên và dãy tượng từ trên cao.' }], access: 'Đi bộ từ ga tàu điện ngầm Odori (nhiều tuyến), ngay trung tâm Sapporo.', mapQuery: 'Odori Park Sapporo', sourceLabel: 'Odori Park official', sourceUrl: 'https://odori-park.jp/en/' },
  { place: 'Lâu đài Hirosaki', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Hirosaki-castle_Aomori_with_Sakura_blossoms.jpg/960px-Hirosaki-castle_Aomori_with_Sakura_blossoms.jpg', prefecture: 'Aomori', time: 'Cuối tháng 4 · hoa anh đào', tip: 'Một trong số ít tháp lâu đài nguyên bản còn lại, giữa biển hoa anh đào.', slug: 'guoc-geta', where: 'Công viên Hirosaki, thành phố Hirosaki, tỉnh Aomori, vùng Tōhoku.', history: 'Lâu đài xây năm 1611 bởi gia tộc Tsugaru thời Edo. Đây là một trong rất ít tháp lâu đài nguyên bản còn sót lại ở Nhật (không phải bản phục dựng bê tông). Công viên quanh lâu đài trồng hơn 2.500 cây anh đào từ thời Minh Trị.', highlights: ['Một trong những điểm ngắm hoa anh đào đẹp nhất Nhật Bản, gồm cả cảnh hoa rơi phủ kín hào nước.', 'Tháp lâu đài nhỏ nhưng là kiến trúc gốc hiếm hoi còn lại từ thời Edo.'], photoSpots: [{ name: 'Cầu qua hào nước', tip: 'Lấy tháp lâu đài phía sau tán anh đào làm hậu cảnh kinh điển.' }, { name: 'Mặt hào phủ hoa', tip: 'Cuối mùa hoa, cánh hoa phủ kín mặt nước tạo lớp "thảm hồng" đặc trưng.' }], access: 'Đi bộ khoảng 15–20 phút từ ga JR Hirosaki, hoặc xe buýt vòng nội thành.', mapQuery: 'Hirosaki Castle Park', sourceLabel: 'Hirosaki Park official', sourceUrl: 'https://www.hirosakipark.jp/' },
  { place: 'Suối nước nóng Dōgo Onsen', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Dogo_onsen_honkan_long_exposure.jpg/960px-Dogo_onsen_honkan_long_exposure.jpg', prefecture: 'Ehime', time: 'Chiều tối · sau tắm', tip: 'Toà nhà onsen gỗ cổ kính, khung cảnh gợi nhớ phim hoạt hình Nhật.', slug: 'ao-len-cardigan', where: 'Khu Dōgo, thành phố Matsuyama, tỉnh Ehime, đảo Shikoku.', history: 'Một trong những suối nước nóng lâu đời nhất Nhật Bản, được nhắc đến trong các thư tịch cổ như Nihon Shoki và Man\'yōshū với lịch sử truyền miệng khoảng 3.000 năm. Toà nhà chính "Dōgo Onsen Honkan" xây năm 1894, được cho là nguồn cảm hứng cho nhà tắm trong phim hoạt hình "Vùng đất linh hồn" (Spirited Away) dù chưa được studio xác nhận chính thức.', highlights: ['Kiến trúc gỗ ba tầng cổ kính hiếm có của một nhà tắm công cộng còn hoạt động.', 'Khu phố quanh onsen có lối đi bộ mái che, quán trà và cửa hàng lưu niệm truyền thống.'], photoSpots: [{ name: 'Mặt tiền Honkan về đêm', tip: 'Đèn lồng lên sáng buổi tối tạo không khí hoài cổ rất rõ.' }, { name: 'Lối đi bộ Dōgo Haikara', tip: 'Phố mua sắm mái che gần đó cho ảnh đời thường ấm áp.' }], access: 'Tàu điện (Botchan Ressha hoặc tram thường) từ ga JR Matsuyama, khoảng 20–25 phút.', mapQuery: 'Dogo Onsen Honkan Matsuyama', sourceLabel: 'Dogo Onsen official', sourceUrl: 'https://www.dogo.jp/en/' },
  { place: 'Thuỷ cung Churaumi', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Okinawa_Aquarium.jpg/960px-Okinawa_Aquarium.jpg', prefecture: 'Okinawa', time: 'Giữa trưa · bể cá sáng rõ', tip: 'Bể "Biển Kuroshio" khổng lồ với cá mập voi tạo khung hình rất ấn tượng.', slug: 'furina', where: 'Công viên Hải dương Ocean Expo, thị trấn Motobu, tỉnh Okinawa.', history: 'Xây dựng cho Triển lãm Đại dương Okinawa năm 1975, cải tạo và mở cửa lại quy mô lớn năm 2002. Bể "Kuroshio" từng là một trong những bể thuỷ cung lớn nhất thế giới khi ra mắt.', highlights: ['Cá mập voi và cá đuối manta bơi trong bể kính khổng lồ là điểm nhấn nổi tiếng nhất.', 'Công viên còn có bãi biển, vườn san hô và đài quan sát hoàng hôn nhìn ra biển Okinawa.'], photoSpots: [{ name: 'Bể Kuroshio chính', tip: 'Đứng giữa để lấy cá mập voi và ánh sáng xanh xuyên qua bể.' }, { name: 'Đường hầm kính', tip: 'Góc thấp nhìn lên tạo cảm giác đang ở trong lòng đại dương.' }], access: 'Xe buýt tốc hành từ sân bay Naha khoảng 2 giờ, hoặc thuê xe tự lái.', mapQuery: 'Okinawa Churaumi Aquarium', sourceLabel: 'Okinawa Churaumi Aquarium official', sourceUrl: 'https://churaumi.okinawa/en/' },
  { place: 'Suối nước nóng Beppu', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Umi_Jigoku_October_2011_02.jpg/960px-Umi_Jigoku_October_2011_02.jpg', prefecture: 'Oita', time: 'Ban ngày · tham quan "địa ngục"', tip: 'Các hồ suối nước nóng màu sắc rực rỡ, không để tắm mà để ngắm.', slug: 'du-nhat', where: 'Thành phố Beppu, tỉnh Oita, đảo Kyushu.', history: 'Beppu là một trong những vùng suối nước nóng lớn nhất Nhật Bản, sản lượng nước nóng đứng thứ nhì thế giới sau Yellowstone. Nổi tiếng với "Beppu Jigoku" (địa ngục Beppu) — các hồ suối nước nóng cảnh quan mang màu sắc khác nhau do khoáng chất, chỉ để ngắm chứ không tắm.', highlights: ['Umi Jigoku (địa ngục biển) có màu xanh coban đặc trưng từ khoáng sunfat sắt.', 'Chinoike Jigoku (địa ngục ao máu) có màu đỏ tự nhiên từ oxit sắt, được ghi nhận là suối nước nóng tự nhiên lâu đời nhất Nhật Bản.'], photoSpots: [{ name: 'Umi Jigoku', tip: 'Chụp cận mặt nước xanh coban với hơi nước bốc nhẹ phía sau.' }, { name: 'Chinoike Jigoku', tip: 'Góc cao nhìn xuống làm nổi bật màu đỏ đặc trưng của hồ.' }], access: 'Xe buýt tham quan "Jigoku Meguri" từ ga JR Beppu, chạy vòng qua các địa ngục chính.', mapQuery: 'Beppu Jigoku Onsen', sourceLabel: 'Beppu City official', sourceUrl: 'https://www.city.beppu.oita.jp/' },
  { place: 'Đảo nghệ thuật Naoshima', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Naoshima_%287046724589%29.jpg/960px-Naoshima_%287046724589%29.jpg', prefecture: 'Kagawa', time: 'Ban ngày · 10:00-16:00', tip: 'Nền bê tông trần và biển Seto hợp trang phục tối giản, một màu.', slug: 'so-mi-trang', where: 'Đảo nhỏ trong biển nội địa Seto, thuộc huyện Kagawa; hai cảng chính là Miyanoura ở phía tây và Honmura ở phía đông.', history: 'Từ cuối thập niên 1980, Naoshima chuyển từ đảo công nghiệp sang đảo bảo tàng theo dự án Benesse Art Site, với nhiều công trình do Tadao Ando thiết kế chìm vào sườn đồi để không che mất đường chân trời.', highlights: ['Bảo tàng, tác phẩm ngoài trời và nhà cổ cải tạo nằm rải khắp đảo chứ không gom vào một khu.', 'Nhiều bảo tàng cấm chụp ảnh bên trong; ảnh đẹp chủ yếu ở tác phẩm ngoài trời và cảnh cảng.'], photoSpots: [{ name: 'Bờ kè Benesse House', tip: 'Lấy biển Seto làm nền phẳng, dáng người đặt lệch một phần ba khung.' }, { name: 'Khu Honmura', tip: 'Tường gỗ cháy yakisugi đen tạo nền tương phản rất mạnh cho đồ sáng màu.' }, { name: 'Cảng Miyanoura', tip: 'Chờ lúc phà cập bến để có thêm lớp chuyển động phía sau.' }], access: 'Phà từ cảng Takamatsu (Kagawa) hoặc cảng Uno (Okayama). Trên đảo có xe buýt nối Miyanoura - Honmura - Tsutsuji-so và shuttle miễn phí tới các bảo tàng.', mapQuery: 'Naoshima Miyanoura Port', sourceLabel: 'JNTO & Benesse Art Site Naoshima', sourceUrl: 'https://www.japan.travel/en/spot/220/' },
  { place: 'Núi thiêng Koyasan', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Danj%C3%B4-garan_%28Wakayama_K%C5%8Dyasan%29_Temple_hdsr_S5_tr02.jpg/960px-Danj%C3%B4-garan_%28Wakayama_K%C5%8Dyasan%29_Temple_hdsr_S5_tr02.jpg', prefecture: 'Wakayama', time: 'Sáng sớm · sương còn đọng', tip: 'Tháp Konpon Daito sơn son làm nền rất hợp áo haori và kimono trầm màu.', slug: 'haori-dang-dai', where: 'Thung lũng trên cao ở huyện Wakayama, vùng Kansai; quần thể khoảng 117 ngôi chùa thuộc Di sản Thế giới.', history: 'Kobo Daishi (Kukai) lập đạo tràng ở đây từ đầu thế kỷ IX làm trung tâm tu học Chân ngôn tông. Danjo Garan là nơi dựng ngôi chùa đầu tiên; Okunoin là nơi đặt lăng của ngài.', highlights: ['Konpon Daito cao 49 mét, tỉ lệ và màu son rất nổi giữa rừng tuyết tùng.', 'Okunoin là đường hành hương dài qua rừng bia mộ cổ; nhiều đoạn cấm chụp ảnh, cần đọc bảng chỉ dẫn trước.'], photoSpots: [{ name: 'Danjo Garan', tip: 'Chụp chính diện Konpon Daito lúc sáng sớm, ít người và ánh sáng dịu.' }, { name: 'Đường vào Okunoin từ Ichinohashi', tip: 'Tuyết tùng cổ thụ và đèn đá tạo chiều sâu; giữ thái độ trang nghiêm, đây là nghĩa trang.' }, { name: 'Cổng Daimon', tip: 'Chiều muộn có ánh sáng xiên rọi vào cổng son đỏ.' }], access: 'Tuyến Nankai Koya đến ga Gokurakubashi (tối thiểu khoảng 90 phút), rồi cáp treo 5 phút lên Koyasan. Từ ga Koyasan đi xe buýt Koya Rinkan: xuống "Kondo-mae" cho Danjo Garan, "Ichinohashi-guchi" cho Okunoin.', mapQuery: 'Danjo Garan Koyasan', sourceLabel: 'Visit Wakayama (trang du lịch chính thức của tỉnh)', sourceUrl: 'https://visitwakayama.jp/en/attractions/detail_481.html' },
  { place: 'Hẻm núi Takachiho', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Takachiho_Gorge_%2852132194587%29.jpg/960px-Takachiho_Gorge_%2852132194587%29.jpg', prefecture: 'Miyazaki', time: 'Giữa buổi sáng · nắng lọt xuống đáy vực', tip: 'Vách đá cột và nước ngọc bích cho nền rất mát, hợp màu lạnh.', slug: 'yukata-xanh', where: 'Thị trấn Takachiho, phía bắc huyện Miyazaki, vùng Kyushu; hẻm núi do dung nham núi Aso nguội lại tạo thành.', history: 'Dòng dung nham cổ nguội đi tạo nên các cột đá lục giác dựng đứng hai bên sông Gokase. Takachiho cũng là vùng đất gắn với truyền thuyết thần đạo về nữ thần mặt trời Amaterasu.', highlights: ['Thác Manai cao 17 mét, nằm trong danh sách 100 thác đẹp của Nhật Bản.', 'Thuê thuyền chèo tay là cách xem thác gần nhất; hết chỗ rất nhanh nên nên đặt trước.'], photoSpots: [{ name: 'Trên thuyền chèo tay', tip: 'Ngồi thấp, lấy thác và vách cột đá làm hai lớp; chống nước cho máy.' }, { name: 'Cầu đi bộ ven vực', tip: 'Góc cao nhìn xuống thuyền tạo tỉ lệ, thấy rõ độ sâu của hẻm núi.' }, { name: 'Đài ngắm thác Manai', tip: 'Phương án thay thế khi thuyền ngừng chạy vì nước lớn.' }], access: 'Không có ga tàu; đi xe buýt từ Kumamoto hoặc Nobeoka tới Takachiho. Thuyền thuê mở 8:30-17:00, đặt trực tuyến từ 9:00 trước ngày đi hai tuần, không nhận đặt qua điện thoại; ngừng chạy khi sông lũ.', mapQuery: 'Takachiho Gorge Manai Falls', sourceLabel: 'Visit Miyazaki (trang du lịch chính thức của tỉnh)', sourceUrl: 'https://www.kanko-miyazaki.jp/en/sightseeing/1001' },
  { place: 'Phố cổ Kurashiki Bikan', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Kurashiki_Bikan_historical_quarter_20190324.jpg/960px-Kurashiki_Bikan_historical_quarter_20190324.jpg', prefecture: 'Okayama', time: 'Chiều vàng · 15:30-17:30', tip: 'Tường trắng namako và hàng liễu ven kênh làm nền sáng, rất tôn màu vải.', slug: 'kimono-hong', where: 'Trung tâm thành phố Kurashiki, huyện Okayama; khu phố kho dọc hai bờ sông Kurashiki.', history: 'Thời Edo, Kurashiki là kho trung chuyển gạo và bông dưới quyền quản lý trực tiếp của Mạc phủ. Những dãy kho tường trắng còn lại đã được cải tạo thành cửa hàng, bảo tàng và quán cà phê.', highlights: ['Kênh đào viền liễu, tường trát trắng và mái ngói tạo một dải phố rất đồng bộ.', 'Bảo tàng Ohara là bảo tàng mỹ thuật phương Tây tư nhân đầu tiên của Nhật Bản; Ivy Square là nhà máy sợi cũ phủ dây thường xuân.'], photoSpots: [{ name: 'Cầu Nakabashi', tip: 'Góc kinh điển lấy cả kênh, liễu và dãy kho trắng trong một khung.' }, { name: 'Thuyền nan trên kênh', tip: 'Ngồi thuyền chụp ngược lên bờ, có thêm mặt nước làm tiền cảnh.' }, { name: 'Kurashiki Ivy Square', tip: 'Tường gạch đỏ phủ thường xuân đổi màu theo mùa, tương phản mạnh với đồ sáng.' }], access: 'Đi bộ khoảng 10 phút từ ga JR Kurashiki. Từ Tokyo, Kyoto, Osaka, Hiroshima hoặc Fukuoka đi Shinkansen tới Shin-Kurashiki rồi chuyển tuyến Sanyo.', mapQuery: 'Kurashiki Bikan Historical Quarter', sourceLabel: 'Okayama Prefecture Official Tourism Guide', sourceUrl: 'https://www.okayama-japan.jp/en/spot/10736' },
  { place: 'Suối nước nóng Ginzan', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Night_in_Ginzan_Onsen_town_January_2022_A.jpg/960px-Night_in_Ginzan_Onsen_town_January_2022_A.jpg', prefecture: 'Yamagata', time: 'Chạng vạng · khi đèn khí vừa bật', tip: 'Đèn khí, nhà gỗ và tuyết cho ánh sáng ấm rất hợp yukata và áo khoác dày.', slug: 'ao-len-co-lo', where: 'Thành phố Obanazawa, huyện Yamagata, vùng Tohoku; dãy nhà trọ gỗ nằm dọc hai bờ một con suối hẹp.', history: 'Tên "Ginzan" nghĩa là núi bạc — vùng này từng có mỏ bạc. Khi mỏ đóng cửa, thị trấn sống bằng suối nước nóng; dãy ryokan gỗ nhiều tầng hiện nay mang phong cách thời Taisho (1912-1926).', highlights: ['Sau khi trời tối, đèn khí bật lên và hắt bóng xuống mặt suối.', 'Lòng đường rất hẹp và là nơi dân cư sinh sống; nên tránh chắn lối trước cửa nhà trọ.'], photoSpots: [{ name: 'Cầu giữa phố', tip: 'Đứng giữa cầu lấy hai dãy nhà gỗ đối xứng hai bên, chụp lúc đèn vừa bật.' }, { name: 'Ashiyu ngâm chân', tip: 'Ảnh sinh hoạt tự nhiên, hơi nước bốc lên làm mềm ánh đèn.' }, { name: 'Cầu Takimi và thác Shirogane', tip: 'Đi hết phố về cuối suối, thác làm hậu cảnh có chuyển động.' }], access: 'Shinkansen Yamagata tới ga Oishida (khoảng 3 giờ 20 phút từ Tokyo), rồi xe buýt 35 phút; xe buýt chỉ chạy cách nhau 60-90 phút. Xe cá nhân nên gửi ở Ginzan Tourist Center rồi đi shuttle vào phố.', mapQuery: 'Ginzan Onsen Obanazawa', sourceLabel: 'JNTO & Tohoku official tourism', sourceUrl: 'https://www.japan.travel/en/spot/1798/' },
  { place: 'Lâu đài Himeji', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Tenshu_of_Himeji_Castle_from_Sannomaru_Square_4.jpg/960px-Tenshu_of_Himeji_Castle_from_Sannomaru_Square_4.jpg', prefecture: 'Hyogo',
    time: 'Sáng · 08:30–10:30', tip: 'Bãi cỏ Sannomaru rộng, đủ khoảng trống để ghép ảnh toàn thân mà vẫn giữ được tháp chính.', slug: 'kimono-hong',
    where: 'Trung tâm thành phố Himeji, tỉnh Hyogo; Sannomaru nằm ngay sau cổng chính của khu thành.',
    history: 'Quần thể hiện nay phát triển mạnh từ đầu thế kỷ XVII. Lâu đài nổi tiếng với ngoại thất trắng và hệ thống phòng thủ nhiều lớp, đồng thời là Di sản Thế giới UNESCO.',
    highlights: ['Tháp chính màu trắng nổi rõ trên nền trời.', 'Bãi Sannomaru cho góc nhìn thoáng, phù hợp ảnh toàn thân.'],
    photoSpots: [{ name: 'Bãi Sannomaru', tip: 'Đứng lệch trái hoặc phải để không che tháp chính.' }, { name: 'Cổng Hishi', tip: 'Chụp sớm để lối vào ít người.' }],
    access: 'Đi bộ khoảng 20 phút từ ga JR Himeji theo đại lộ Otemae.', mapQuery: 'Himeji Castle Sannomaru Square', sourceLabel: 'Himeji City official tourism', sourceUrl: 'https://visit-himeji.com/en/sightseeing/himeji-castle/' },
  { place: 'Chùa Sensō-ji · Asakusa', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Hozomon_%28main_gate%29%2C_Sensoji_Temple%2C_Asakusa%2C_Tokyo.jpg/960px-Hozomon_%28main_gate%29%2C_Sensoji_Temple%2C_Asakusa%2C_Tokyo.jpg', prefecture: 'Tokyo',
    time: 'Sáng sớm · trước 08:00', tip: 'Sân lát đá trước Hōzōmon cho điểm đặt chân rõ; nên dùng trang phục kín đáo và đứng lệch cổng.', slug: 'yukata-xanh',
    where: 'Khu Asakusa, quận Taitō, Tokyo; trục tham quan đi từ Kaminarimon qua Nakamise tới chính điện.',
    history: 'Sensō-ji có lịch sử lâu đời và là một trong những ngôi chùa tiêu biểu của Tokyo. Khuôn viên được tái thiết sau chiến tranh và tiếp tục là trung tâm tín ngưỡng, lễ hội của Asakusa.',
    highlights: ['Đèn lồng lớn và kiến trúc sơn son của Hōzōmon.', 'Phố Nakamise nối cổng ngoài với khu chùa.'],
    photoSpots: [{ name: 'Sân Hōzōmon', tip: 'Đứng lệch sang mép sân để giữ trọn cổng phía sau.' }, { name: 'Kaminarimon', tip: 'Đến trước giờ hàng quán mở để nền ít người.' }],
    access: 'Đi bộ vài phút từ ga Asakusa của Tokyo Metro, Toei hoặc Tobu.', mapQuery: 'Sensoji Hozomon Asakusa', sourceLabel: 'Sensō-ji official', sourceUrl: 'https://www.senso-ji.jp/english/' },
  { place: 'Vườn Okayama Kōrakuen', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Okayama_Korakuen_01.jpg/960px-Okayama_Korakuen_01.jpg', prefecture: 'Okayama',
    time: 'Sáng · ánh sáng dịu', tip: 'Mảng cỏ lớn phía trước hồ cảnh phù hợp ghép người ở tỉ lệ nhỏ vừa, tạo cảm giác đang đứng trong vườn.', slug: 'haori-dang-dai',
    where: 'Thành phố Okayama, cạnh sông Asahi và đối diện Lâu đài Okayama.',
    history: 'Kōrakuen được hình thành dưới thời lãnh chúa Ikeda vào cuối thế kỷ XVII. Khu vườn dùng các bãi cỏ, ao, đồi và nhà trà để tạo nhiều lớp cảnh quan.',
    highlights: ['Thảm cỏ rộng hiếm thấy trong vườn Nhật truyền thống.', 'Hồ Sawa-no-ike và Lâu đài Okayama tạo hậu cảnh nhiều lớp.'],
    photoSpots: [{ name: 'Bãi cỏ Enyō-tei', tip: 'Ghép người về bên trái, tránh hàng rào và mặt nước phía trước.' }, { name: 'Bờ hồ Sawa-no-ike', tip: 'Dùng cây tỉa và cầu nhỏ làm đường dẫn.' }],
    access: 'Xe điện từ ga Okayama tới Shiroshita rồi đi bộ, hoặc xe buýt thẳng tới vườn.', mapQuery: 'Okayama Korakuen Garden', sourceLabel: 'Okayama Kōrakuen official', sourceUrl: 'https://okayama-korakuen.jp/section/english/index.html' },
  { place: 'Vườn Sengan-en', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Sengan-en_%284549028031%29.jpg/960px-Sengan-en_%284549028031%29.jpg', prefecture: 'Kagoshima',
    time: 'Sáng quang mây', tip: 'Bãi cỏ phía trước đủ rộng để ghép toàn thân, còn Sakurajima nằm xa nên không bị người che.', slug: 'so-mi-trang',
    where: 'Ven vịnh Kinkō, phía bắc trung tâm thành phố Kagoshima.',
    history: 'Sengan-en được gia tộc Shimadzu xây dựng từ thế kỷ XVII. Khu vườn mượn núi Sakurajima và vịnh Kinkō làm cảnh quan nền.',
    highlights: ['Núi lửa Sakurajima hiện ra trực diện qua vịnh.', 'Vườn, dinh thự và dấu tích công nghiệp của gia tộc Shimadzu cùng nằm trong khuôn viên.'],
    photoSpots: [{ name: 'Bãi cỏ hướng Sakurajima', tip: 'Đặt người lệch trái để núi vẫn nhìn rõ.' }, { name: 'Vườn trước dinh thự', tip: 'Trang phục truyền thống hợp các lớp cây tỉa và đá cảnh.' }],
    access: 'Xe buýt tham quan từ ga Kagoshima-Chūō hoặc trung tâm thành phố.', mapQuery: 'Sengan-en Kagoshima', sourceLabel: 'Kagoshima City official tourism', sourceUrl: 'https://www.kagoshima-yokanavi.jp/en/spot/10006' },
  { place: 'Phố samurai Kakunodate', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Bukeyashiki_Street_in_Kakunodate_20161106b.jpg/960px-Bukeyashiki_Street_in_Kakunodate_20161106b.jpg', prefecture: 'Akita',
    time: 'Chiều · mùa lá đỏ', tip: 'Trục đường thẳng tạo phối cảnh tự nhiên; ghép người ở giữa đường với bóng đổ nhẹ.', slug: 'ao-len-co-lo',
    where: 'Khu Kakunodate, thành phố Semboku, tỉnh Akita.',
    history: 'Khu phố giữ lại bố cục và nhiều dinh thự của các gia đình samurai thời Edo. Hàng rào đen, cây cổ thụ và cổng nhà tạo cảnh quan thống nhất.',
    highlights: ['Dãy bukeyashiki và hàng rào gỗ đen.', 'Hoa anh đào mùa xuân và lá đỏ mùa thu thay đổi hoàn toàn sắc phố.'],
    photoSpots: [{ name: 'Đường Bukeyashiki', tip: 'Đứng giữa trục phối cảnh, tránh che người đi bộ ở xa.' }, { name: 'Nhà Aoyagi', tip: 'Chụp trước cổng và tường đen, tôn trang phục sáng.' }],
    access: 'Đi bộ khoảng 15–20 phút từ ga JR Kakunodate.', mapQuery: 'Kakunodate Samurai District', sourceLabel: 'Tazawako Kakunodate official tourism', sourceUrl: 'https://tazawako-kakunodate.com/en/spots/5996/' },
  { place: 'Cánh đồng hoa Farm Tomita', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Farm_Tomita_20140812-7.jpg/960px-Farm_Tomita_20140812-7.jpg', prefecture: 'Hokkaido',
    time: 'Sáng · mùa hoa', tip: 'Lối đất giữa hai luống hoa tạo vùng đứng hẹp nhưng rõ, không khiến người đè lên hoa.', slug: 'so-mi-trang',
    where: 'Thị trấn Nakafurano, trung tâm Hokkaido.',
    history: 'Farm Tomita phát triển từ nông trại trồng oải hương và trở thành địa điểm ngắm các dải hoa theo mùa nổi tiếng của Furano.',
    highlights: ['Các luống oải hương tím xếp thành đường dẫn sâu vào khung.', 'Nhiều khu hoa đổi màu theo thời điểm nở.'],
    photoSpots: [{ name: 'Lối giữa luống oải hương', tip: 'Đặt chân đúng lối đất, không ghép người lên luống hoa.' }, { name: 'Irodori Field', tip: 'Dùng các dải màu song song làm hậu cảnh.' }],
    access: 'Mùa hè có ga Lavender-Farm; ngoài mùa đi từ ga Nakafurano bằng taxi hoặc đi bộ.', mapQuery: 'Farm Tomita Nakafurano', sourceLabel: 'Farm Tomita official', sourceUrl: 'https://www.farm-tomita.co.jp/en/' },
  { place: 'Phố trà Higashi Chaya', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Higashi_Chaya_district%2C_Kanazawa_%283810704024%29.jpg/960px-Higashi_Chaya_district%2C_Kanazawa_%283810704024%29.jpg', prefecture: 'Ishikawa',
    time: 'Sáng sớm · sau mưa nhẹ', tip: 'Lối lát đá giữa hai dãy nhà gỗ tạo khung chân thực cho kimono và yukata.', slug: 'kimono-hong',
    where: 'Bờ đông sông Asano, thành phố Kanazawa, tỉnh Ishikawa.',
    history: 'Higashi Chaya là một trong các khu nhà trà lịch sử của Kanazawa, phát triển từ thời Edo. Mặt tiền gỗ dạng lưới vẫn được bảo tồn dọc các phố chính.',
    highlights: ['Hai dãy chaya gỗ tạo phối cảnh cân xứng.', 'Một số nhà trà lịch sử mở cửa tham quan và biểu diễn nghệ thuật truyền thống.'],
    photoSpots: [{ name: 'Phố chính Higashi Chaya', tip: 'Ghép người giữa lối, dùng mặt đường ướt để nhận bóng nhẹ.' }, { name: 'Bờ sông Asano', tip: 'Chuyển sang góc thoáng khi phố đông.' }],
    access: 'Xe buýt từ ga Kanazawa tới Hashibachō rồi đi bộ vài phút.', mapQuery: 'Higashi Chaya District Kanazawa', sourceLabel: 'Kanazawa City official tourism', sourceUrl: 'https://visitkanazawa.jp/en/attractions/detail_10212.html' },
  { place: 'Công viên Moerenuma', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Avenue_in_Moerenuma_Park.jpg/960px-Avenue_in_Moerenuma_Park.jpg', prefecture: 'Hokkaido',
    time: 'Trưa · trời xanh', tip: 'Đường cong và thảm cỏ trống phù hợp trang phục hiện đại, ảnh toàn thân ít vật cản.', slug: 'blazer-kaki',
    where: 'Quận Higashi, thành phố Sapporo, Hokkaido.',
    history: 'Công viên được thiết kế tổng thể theo ý tưởng biến toàn bộ khu đất thành một tác phẩm điêu khắc. Không gian kết hợp gò cỏ, mặt nước và công trình hình học.',
    highlights: ['Trục cây và đường cong tối giản.', 'Các công trình kính, gò nhân tạo và đài phun nước tạo nhiều phong cách nền.'],
    photoSpots: [{ name: 'Đại lộ xanh', tip: 'Đặt người trên cỏ bên phải hoặc lối đi bên trái.' }, { name: 'Hidamari Glass Pyramid', tip: 'Hợp outfit phố và vật liệu hiện đại.' }],
    access: 'Từ trung tâm Sapporo đi tàu điện ngầm và chuyển xe buýt; kiểm tra lịch theo mùa.', mapQuery: 'Moerenuma Park Sapporo', sourceLabel: 'Moerenuma Park official', sourceUrl: 'https://moerenumapark.jp/english/' },
  { place: 'Công viên hoa Ashikaga', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Japanese_wisteria%2C_Ashikaga_Flower_Park_14.jpg/960px-Japanese_wisteria%2C_Ashikaga_Flower_Park_14.jpg', prefecture: 'Tochigi',
    time: 'Sáng · mùa tử đằng', tip: 'Lối lát trống ở mép vườn cho phép ghép người mà không che giàn hoa tím.', slug: 'yukata-xanh',
    where: 'Thành phố Ashikaga, tỉnh Tochigi, vùng Kantō.',
    history: 'Công viên nổi tiếng với các cây tử đằng lâu năm được chăm sóc thành giàn lớn. Mùa hoa chính thường thu hút đông khách nên khung cảnh trống phù hợp nhất vào đầu giờ.',
    highlights: ['Giàn tử đằng tím và trắng tạo tán hoa lớn.', 'Các khu vườn theo mùa và chiếu sáng buổi tối tạo nhiều bảng màu nền.'],
    photoSpots: [{ name: 'Lối cạnh giàn tử đằng', tip: 'Đặt người bên trái, giữ tán hoa làm điểm chính bên phải.' }, { name: 'Đường hầm hoa trắng', tip: 'Chụp dọc để tăng chiều sâu.' }],
    access: 'Đi bộ ngắn từ ga Ashikaga Flower Park trên tuyến JR Ryōmō.', mapQuery: 'Ashikaga Flower Park', sourceLabel: 'Ashikaga Flower Park official', sourceUrl: 'https://www.ashikaga.co.jp/english/' },
  { place: 'Vườn Shinjuku Gyoen', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Shinjuku_Gyoen_National_Garden_and_NTT_DoCoMo_Yoyogi_Building%2C_Tokyo%2C_Japan.jpg/960px-Shinjuku_Gyoen_National_Garden_and_NTT_DoCoMo_Yoyogi_Building%2C_Tokyo%2C_Japan.jpg', prefecture: 'Tokyo',
    time: 'Sáng · ngày nắng', tip: 'Thảm cỏ phẳng, không người và hậu cảnh đô thị xa giúp ghép ảnh toàn thân tự nhiên nhất.', slug: 'haori-dang-dai',
    where: 'Giữa Shinjuku và Sendagaya, trung tâm Tokyo.',
    history: 'Khu vườn từng là đất của gia tộc Naitō, sau đó được phát triển thành vườn hoàng gia và mở cửa công cộng. Không gian kết hợp vườn cảnh quan, vườn Nhật và các thảm cỏ rộng.',
    highlights: ['Mảng cỏ rộng tương phản với đường chân trời Shinjuku.', 'Nhiều phong cách vườn và mùa hoa trong cùng khuôn viên.'],
    photoSpots: [{ name: 'Thảm cỏ nhìn tháp NTT Docomo', tip: 'Đứng lệch trái để tháp vẫn hiện ở mép phải.' }, { name: 'Vườn Nhật', tip: 'Chọn góc có lối đất, tránh ghép người lên mặt hồ.' }],
    access: 'Đi bộ từ ga Shinjuku-gyoemmae, Shinjuku-sanchōme hoặc Sendagaya.', mapQuery: 'Shinjuku Gyoen National Garden', sourceLabel: 'Ministry of the Environment, Japan', sourceUrl: 'https://www.env.go.jp/garden/shinjukugyoen/english/' },
  { place: 'Đền Meiji Jingu', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Meiji-jingu_Torii_2.jpg/960px-Meiji-jingu_Torii_2.jpg', prefecture: 'Tokyo',
    time: 'Sáng sớm · ít người', tip: 'Lối sỏi rộng và rừng cây tối làm nền trầm; kimono sáng màu nổi rõ khi đứng giữa hai cột torii.', slug: 'kimono-hong',
    where: 'Trong rừng Meiji Jingu, sát ga Harajuku và công viên Yoyogi, Tokyo.',
    history: 'Đền thờ Thiên hoàng Meiji và Hoàng hậu Shōken, khánh thành năm 1920. Khu rừng bao quanh gồm hơn 100.000 cây do người dân cả nước quyên góp trồng.',
    highlights: ['Cổng torii gỗ hinoki cao 12m ở lối vào chính.', 'Đường sỏi rộng dưới tán rừng, đi bộ khoảng 10 phút tới chính điện.'],
    photoSpots: [{ name: 'Cổng torii lối vào', tip: 'Đứng giữa hai cột, lùi đủ xa để lấy trọn thanh ngang phía trên.' }, { name: 'Đường sỏi trong rừng', tip: 'Sáng sớm ánh sáng xuyên tán cây, ít khách qua lại.' }],
    access: 'Đi bộ 1 phút từ ga JR Harajuku hoặc ga Meiji-jingumae.', mapQuery: 'Meiji Jingu', sourceLabel: 'Meiji Jingu official', sourceUrl: 'https://www.meijijingu.or.jp/en/' },
  { place: 'Cầu Kintai-kyō', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Iwakuni%2C_ponte_kintai-kyo%2C_00.jpg/960px-Iwakuni%2C_ponte_kintai-kyo%2C_00.jpg', prefecture: 'Yamaguchi',
    time: 'Chiều muộn · nắng vàng', tip: 'Bãi sỏi dưới cầu rộng và phẳng, đứng giữa hai trụ đá để lấy trọn nhịp cầu phía sau.', slug: 'haori-dang-dai',
    where: 'Bắc qua sông Nishiki ở Iwakuni, tỉnh Yamaguchi.',
    history: 'Cầu gỗ năm nhịp vòm dựng lần đầu năm 1673, nhiều lần bị lũ cuốn và được dựng lại theo đúng kỹ thuật mộng gỗ truyền thống, gần nhất là năm 1953.',
    highlights: ['Năm nhịp vòm gỗ tựa trên trụ đá xếp khan.', 'Bãi sỏi lòng sông đi bộ được vào mùa nước cạn.'],
    photoSpots: [{ name: 'Bãi sỏi dưới nhịp giữa', tip: 'Đứng lệch phải để hai nhịp trái vẫn nằm trong khung.' }, { name: 'Bờ sông phía đông', tip: 'Chiều muộn ánh nắng xiên làm nổi vân gỗ mặt cầu.' }],
    access: 'Xe buýt khoảng 20 phút từ ga JR Iwakuni tới bến Kintaikyo.', mapQuery: 'Kintai Bridge Iwakuni', sourceLabel: 'Iwakuni City Tourism', sourceUrl: 'https://kintaikyo.iwakuni-city.net/' },
];

export function regionsList(): string[] {
  const order = ['Hokkaido', 'Tōhoku', 'Kantō', 'Chūbu', 'Kansai', 'Chūgoku', 'Shikoku', 'Kyūshū & Okinawa'];
  const present = new Set(SPOTS.map(s => REGION_OF_PREFECTURE[s.prefecture]));
  return order.filter(r => present.has(r));
}
export function prefecturesInRegion(region: string): string[] {
  const present = new Set(SPOTS.filter(s => REGION_OF_PREFECTURE[s.prefecture] === region).map(s => s.prefecture));
  return [...present];
}
export function spotsInPrefecture(prefecture: string): JapanSpot[] {
  return SPOTS.filter(s => s.prefecture === prefecture);
}

/**
 * Chiều ngược lại của `spotsInPrefecture`: một món đồ hợp mặc ở những đâu.
 *
 * Trang sản phẩm dùng hàm này để nói cụ thể "mặc bộ này ở đâu, vào giờ nào,
 * vì sao hợp" thay vì một câu quảng cáo chung chung. Dữ liệu vẫn là cùng một
 * bảng SPOTS, nên không có nguy cơ hai nơi mô tả lệch nhau.
 */
export function spotsForProduct(slug: string): JapanSpot[] {
  const key = String(slug || '').trim();
  if (!key) return [];
  return SPOTS.filter(spot => spot.slug === key);
}

/** Các tỉnh có địa điểm hợp với món đồ này, giữ nguyên thứ tự xuất hiện. */
export function prefecturesForProduct(slug: string): string[] {
  return [...new Set(spotsForProduct(slug).map(spot => spot.prefecture))];
}
